/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  SiteHealthSummary,
  HyperVSitesGetSiteHealthSummaryOptionalParams,
  HyperVSitesGetSiteOptionalParams,
  HyperVSitesGetSiteResponse,
  HyperVSite,
  HyperVSitesPutSiteOptionalParams,
  HyperVSitesPutSiteResponse,
  HyperVSitesDeleteSiteOptionalParams,
  HyperVSitesPatchSiteOptionalParams,
  HyperVSitesPatchSiteResponse,
  HyperVSitesRefreshSiteOptionalParams,
  HyperVSitesRefreshSiteResponse,
  HyperVSitesGetSiteUsageOptionalParams,
  HyperVSitesGetSiteUsageResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a HyperVSites. */
export interface HyperVSites {
  /**
   * Method to get site health summary.
   * @param subscriptionId The ID of the target subscription.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param options The options parameters.
   */
  listSiteHealthSummary(
    subscriptionId: string,
    resourceGroupName: string,
    siteName: string,
    options?: HyperVSitesGetSiteHealthSummaryOptionalParams
  ): PagedAsyncIterableIterator<SiteHealthSummary>;
  /**
   * Method to get a site.
   * @param subscriptionId The ID of the target subscription.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param options The options parameters.
   */
  getSite(
    subscriptionId: string,
    resourceGroupName: string,
    siteName: string,
    options?: HyperVSitesGetSiteOptionalParams
  ): Promise<HyperVSitesGetSiteResponse>;
  /**
   * Method to create or update a site.
   * @param subscriptionId The ID of the target subscription.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param body Body with site details.
   * @param options The options parameters.
   */
  putSite(
    subscriptionId: string,
    resourceGroupName: string,
    siteName: string,
    body: HyperVSite,
    options?: HyperVSitesPutSiteOptionalParams
  ): Promise<HyperVSitesPutSiteResponse>;
  /**
   * Method to delete a site.
   * @param subscriptionId The ID of the target subscription.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param options The options parameters.
   */
  deleteSite(
    subscriptionId: string,
    resourceGroupName: string,
    siteName: string,
    options?: HyperVSitesDeleteSiteOptionalParams
  ): Promise<void>;
  /**
   * Method to patch an existing site.
   * @param subscriptionId The ID of the target subscription.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param body Body with site details.
   * @param options The options parameters.
   */
  patchSite(
    subscriptionId: string,
    resourceGroupName: string,
    siteName: string,
    body: HyperVSite,
    options?: HyperVSitesPatchSiteOptionalParams
  ): Promise<HyperVSitesPatchSiteResponse>;
  /**
   * Method to refresh a site.
   * @param subscriptionId The ID of the target subscription.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param options The options parameters.
   */
  refreshSite(
    subscriptionId: string,
    resourceGroupName: string,
    siteName: string,
    options?: HyperVSitesRefreshSiteOptionalParams
  ): Promise<HyperVSitesRefreshSiteResponse>;
  /**
   * Method to get site usage.
   * @param subscriptionId The ID of the target subscription.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param siteName Site name.
   * @param options The options parameters.
   */
  getSiteUsage(
    subscriptionId: string,
    resourceGroupName: string,
    siteName: string,
    options?: HyperVSitesGetSiteUsageOptionalParams
  ): Promise<HyperVSitesGetSiteUsageResponse>;
}
