// Licensed under the MIT license.

export {
  DeviceRegistryClient,
  DeviceRegistryClientOptions,
} from "./deviceRegistryClient.js";
export {
  Resource,
  SystemData,
  CreatedByType,
  TrackedResource,
  AssetEndpointProfile,
  AssetEndpointProfileProperties,
  UserAuthentication,
  UserAuthenticationMode,
  UsernamePasswordCredentials,
  X509Credentials,
  TransportAuthentication,
  OwnCertificate,
  ResourceProvisioningState,
  ExtendedLocation,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  AssetEndpointProfileUpdate,
  AssetEndpointProfileUpdateProperties,
  Asset,
  AssetProperties,
  DataPoint,
  DataPointsObservabilityMode,
  Event,
  EventsObservabilityMode,
  AssetStatus,
  AssetStatusError,
  AssetUpdate,
  AssetUpdateProperties,
  OperationStatusResult,
  Operation,
  OperationDisplay,
  Origin,
  ActionType,
  Versions,
  ProvisioningState,
  OperationsListOptionalParams,
  OperationStatusGetOptionalParams,
  AssetsGetOptionalParams,
  AssetsCreateOrReplaceOptionalParams,
  AssetsUpdateOptionalParams,
  AssetsDeleteOptionalParams,
  AssetsListByResourceGroupOptionalParams,
  AssetsListBySubscriptionOptionalParams,
  AssetEndpointProfilesGetOptionalParams,
  AssetEndpointProfilesCreateOrReplaceOptionalParams,
  AssetEndpointProfilesUpdateOptionalParams,
  AssetEndpointProfilesDeleteOptionalParams,
  AssetEndpointProfilesListByResourceGroupOptionalParams,
  AssetEndpointProfilesListBySubscriptionOptionalParams,
} from "./models/index.js";
export {
  AssetEndpointProfilesOperations,
  AssetsOperations,
  OperationsOperations,
  OperationStatusOperations,
} from "./classic/index.js";
