# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
            
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/cosmosdbmongocluster/arm-cosmosdb-mongocluster
      - sdk/cosmosdbmongocluster/ci.mgmt.yml

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/cosmosdbmongocluster/arm-cosmosdb-mongocluster
      - sdk/cosmosdbmongocluster/ci.mgmt.yml

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: cosmosdbmongocluster
    Artifacts:
      - name: azure-arm-cosmosdb-mongocluster
        safeName: azurearmcosmosdbmongocluster
        