/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  Alert,
  AlertsListOptionalParams,
  AlertsGetOptionalParams,
  AlertsGetResponse,
  AlertsCreateOptionalParams,
  AlertsCreateResponse,
  AlertsDeleteOptionalParams,
  AlertsDeleteResponse,
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a Alerts. */
export interface Alerts {
  /**
   * Gets a list of alerts in the specified SAP monitor. The operations returns various properties of
   * each alerts.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param monitorName Name of the SAP monitor resource.
   * @param options The options parameters.
   */
  list(
    resourceGroupName: string,
    monitorName: string,
    options?: AlertsListOptionalParams,
  ): PagedAsyncIterableIterator<Alert>;
  /**
   * Gets properties of an alert for the specified subscription, resource group, SAP monitor name, and
   * resource name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param monitorName Name of the SAP monitor resource.
   * @param alertName Name of the SAP monitor alert resource.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    monitorName: string,
    alertName: string,
    options?: AlertsGetOptionalParams,
  ): Promise<AlertsGetResponse>;
  /**
   * Creates an alert for the specified subscription, resource group, SAP monitor name, and resource
   * name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param monitorName Name of the SAP monitor resource.
   * @param alertName Name of the SAP monitor alert resource.
   * @param resource Request body representing a SAP monitor's alert resource
   * @param options The options parameters.
   */
  beginCreate(
    resourceGroupName: string,
    monitorName: string,
    alertName: string,
    resource: Alert,
    options?: AlertsCreateOptionalParams,
  ): Promise<
    SimplePollerLike<OperationState<AlertsCreateResponse>, AlertsCreateResponse>
  >;
  /**
   * Creates an alert for the specified subscription, resource group, SAP monitor name, and resource
   * name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param monitorName Name of the SAP monitor resource.
   * @param alertName Name of the SAP monitor alert resource.
   * @param resource Request body representing a SAP monitor's alert resource
   * @param options The options parameters.
   */
  beginCreateAndWait(
    resourceGroupName: string,
    monitorName: string,
    alertName: string,
    resource: Alert,
    options?: AlertsCreateOptionalParams,
  ): Promise<AlertsCreateResponse>;
  /**
   * Deletes an alert for the specified subscription, resource group, SAP monitor name, and resource
   * name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param monitorName Name of the SAP monitor resource.
   * @param alertName Name of the SAP monitor alert resource.
   * @param options The options parameters.
   */
  beginDelete(
    resourceGroupName: string,
    monitorName: string,
    alertName: string,
    options?: AlertsDeleteOptionalParams,
  ): Promise<
    SimplePollerLike<OperationState<AlertsDeleteResponse>, AlertsDeleteResponse>
  >;
  /**
   * Deletes an alert for the specified subscription, resource group, SAP monitor name, and resource
   * name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param monitorName Name of the SAP monitor resource.
   * @param alertName Name of the SAP monitor alert resource.
   * @param options The options parameters.
   */
  beginDeleteAndWait(
    resourceGroupName: string,
    monitorName: string,
    alertName: string,
    options?: AlertsDeleteOptionalParams,
  ): Promise<AlertsDeleteResponse>;
}
