// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { MigrateClient } from "./migrateClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  AvsAssessmentV2,
  AvsAssessmentPropertiesV2,
  KnownProvisioningState,
  ProvisioningState,
  Scope,
  KnownScopeType,
  ScopeType,
  AvsAssessmentSettings,
  KnownAzureCurrency,
  AzureCurrency,
  KnownAssessmentSizingCriterion,
  AssessmentSizingCriterion,
  PerformanceData,
  KnownPercentile,
  Percentile,
  KnownTimeRange,
  TimeRange,
  SavingsSettings,
  KnownSavingsOptions,
  SavingsOptions,
  KnownAzureOffer,
  AzureOffer,
  BillingSettings,
  KnownLicensingProgram,
  LicensingProgram,
  KnownEnvironmentType,
  EnvironmentType,
  KnownFttAndRaidLevel,
  FttAndRaidLevel,
  KnownAzureAvsNodeType,
  AzureAvsNodeType,
  KnownAvsAssessmentScenario,
  AvsAssessmentScenario,
  KnownExternalStorageType,
  ExternalStorageType,
  AssessmentDetails,
  KnownAssessmentStatus,
  AssessmentStatus,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  DownloadUrl,
  AvsAssessedMachineV2,
  AvsAssessedMachinePropertiesV2,
  KnownMigrateWorkloadType,
  MigrateWorkloadType,
  Linkages,
  KnownLinkageType,
  LinkageType,
  KnownLinkageKind,
  LinkageKind,
  AvsRecommendationsMigrationIssuesMigrationSuitabilitySkus,
  Configuration,
  KnownAzureTarget,
  AzureTarget,
  RecommendedFor,
  KnownStrategyType,
  StrategyType,
  KnownMigrationPlatform,
  MigrationPlatform,
  MigrationSuitability,
  KnownCloudSuitabilityCommon,
  CloudSuitabilityCommon,
  SecuritySuitability,
  CostDetailsCommon,
  NameValuePairCostType,
  KnownCostType,
  CostType,
  SavingsDetailsCommon,
  NameValuePairSavingsType,
  KnownSavingsType,
  SavingsType,
  MigrationIssues,
  KnownMigrationIssuesCategory,
  MigrationIssuesCategory,
  MoreInformation,
  SkusMigrationSuitability,
  KnownSkuKind,
  SkuKind,
  KnownSkuType,
  SkuType,
  SourceRecommendationMigrationSuitability,
  SkuDetails,
  NameValuePair,
  AvsAssessedMachineExtendedDetails,
  ErrorModel,
  AvsAssessedDiskV2,
  AvsAssessedNetworkAdapter,
  KnownMachineBootType,
  MachineBootType,
  KnownGuestOperatingSystemArchitecture,
  GuestOperatingSystemArchitecture,
  KnownAssessedMachineType,
  AssessedMachineType,
  AvsAssessmentV2Summary,
  AvsAssessmentSummaryPropertiesV2,
  KnownSummaryType,
  SummaryType,
  SourceDetails,
  KnownAssessmentSource,
  AssessmentSource,
  TargetDetails,
  TargetSourcePair,
  MigrationDetails,
  NameValuePairCloudSuitabilityCommon,
  KnownMigrationType,
  MigrationType,
  ManagementDetails,
  KnownAzureManagementOfferingType,
  AzureManagementOfferingType,
  KnownCloudSuitability,
  CloudSuitability,
  KnownAzureAvsSuitabilityExplanation,
  AzureAvsSuitabilityExplanation,
  AvsEstimatedNode,
  KnownAzureReservedInstance,
  AzureReservedInstance,
  AvsEstimatedExternalStorage,
  AvsEstimatedNetwork,
  KnownNetworkSkuType,
  NetworkSkuType,
  AvsGraphAssessmentOptions,
  AvsGraphAssessmentOptionsProperties,
  AvsAssessmentOptionsOutboundEdgeGroup,
  KnownAzureLocation,
  AzureLocation,
  KnownAvsApiVersions,
} from "./models/index.js";
export { MigrateClientOptionalParams } from "./api/index.js";
export {
  AvsAssessedMachinesV2OperationsListByParentOptionalParams,
  AvsAssessedMachinesV2OperationsGetOptionalParams,
} from "./api/avsAssessedMachinesV2Operations/index.js";
export {
  AvsAssessmentsV2OperationsDownloadUrlOptionalParams,
  AvsAssessmentsV2OperationsDeleteOptionalParams,
  AvsAssessmentsV2OperationsCreateOptionalParams,
  AvsAssessmentsV2OperationsListByParentOptionalParams,
  AvsAssessmentsV2OperationsGetOptionalParams,
} from "./api/avsAssessmentsV2Operations/index.js";
export {
  AvsAssessmentV2SummaryOperationsListByParentOptionalParams,
  AvsAssessmentV2SummaryOperationsGetOptionalParams,
} from "./api/avsAssessmentV2SummaryOperations/index.js";
export {
  AvsGraphAssessmentOptionsOperationsListByParentOptionalParams,
  AvsGraphAssessmentOptionsOperationsGetOptionalParams,
} from "./api/avsGraphAssessmentOptionsOperations/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  AvsAssessedMachinesV2OperationsOperations,
  AvsAssessmentsV2OperationsOperations,
  AvsAssessmentV2SummaryOperationsOperations,
  AvsGraphAssessmentOptionsOperationsOperations,
  OperationsOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
