// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { ScVmmClient } from "./scVmmClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  VmmServer,
  VmmServerProperties,
  VmmCredential,
  KnownProvisioningState,
  ProvisioningState,
  ExtendedLocation,
  TrackedResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  VmmServerTagsUpdate,
  Cloud,
  CloudProperties,
  CloudCapacity,
  StorageQosPolicy,
  CloudTagsUpdate,
  VirtualNetwork,
  VirtualNetworkProperties,
  VirtualNetworkTagsUpdate,
  VirtualMachineTemplate,
  VirtualMachineTemplateProperties,
  KnownOsType,
  OsType,
  KnownLimitCpuForMigration,
  LimitCpuForMigration,
  KnownDynamicMemoryEnabled,
  DynamicMemoryEnabled,
  KnownIsCustomizable,
  IsCustomizable,
  KnownIsHighlyAvailable,
  IsHighlyAvailable,
  NetworkInterface,
  KnownAllocationMethod,
  AllocationMethod,
  VirtualDisk,
  StorageQosPolicyDetails,
  KnownCreateDiffDisk,
  CreateDiffDisk,
  VirtualMachineTemplateTagsUpdate,
  AvailabilitySet,
  AvailabilitySetProperties,
  AvailabilitySetTagsUpdate,
  InventoryItem,
  InventoryItemProperties,
  InventoryItemPropertiesUnion,
  KnownInventoryType,
  InventoryType,
  CloudInventoryItem,
  VirtualNetworkInventoryItem,
  VirtualMachineTemplateInventoryItem,
  VirtualMachineInventoryItem,
  InventoryItemDetails,
  ProxyResource,
  VirtualMachineInstance,
  VirtualMachineInstanceProperties,
  AvailabilitySetListItem,
  OsProfileForVmInstance,
  HardwareProfile,
  NetworkProfile,
  StorageProfile,
  InfrastructureProfile,
  Checkpoint,
  ExtensionResource,
  VirtualMachineInstanceUpdate,
  VirtualMachineInstanceUpdateProperties,
  HardwareProfileUpdate,
  NetworkProfileUpdate,
  NetworkInterfaceUpdate,
  StorageProfileUpdate,
  VirtualDiskUpdate,
  InfrastructureProfileUpdate,
  StopVirtualMachineOptions,
  KnownSkipShutdown,
  SkipShutdown,
  VirtualMachineCreateCheckpoint,
  VirtualMachineDeleteCheckpoint,
  VirtualMachineRestoreCheckpoint,
  VmInstanceHybridIdentityMetadata,
  VmInstanceHybridIdentityMetadataProperties,
  GuestAgent,
  GuestAgentProperties,
  GuestCredential,
  HttpProxyConfiguration,
  KnownProvisioningAction,
  ProvisioningAction,
  KnownForceDelete,
  ForceDelete,
  KnownDeleteFromHost,
  DeleteFromHost,
  KnownVersions,
} from "./models/index.js";
export { ScVmmClientOptionalParams } from "./api/index.js";
export {
  AvailabilitySetsListBySubscriptionOptionalParams,
  AvailabilitySetsListByResourceGroupOptionalParams,
  AvailabilitySetsDeleteOptionalParams,
  AvailabilitySetsUpdateOptionalParams,
  AvailabilitySetsCreateOrUpdateOptionalParams,
  AvailabilitySetsGetOptionalParams,
} from "./api/availabilitySets/index.js";
export {
  CloudsListBySubscriptionOptionalParams,
  CloudsListByResourceGroupOptionalParams,
  CloudsDeleteOptionalParams,
  CloudsUpdateOptionalParams,
  CloudsCreateOrUpdateOptionalParams,
  CloudsGetOptionalParams,
} from "./api/clouds/index.js";
export {
  GuestAgentsListByVirtualMachineInstanceOptionalParams,
  GuestAgentsDeleteOptionalParams,
  GuestAgentsCreateOptionalParams,
  GuestAgentsGetOptionalParams,
} from "./api/guestAgents/index.js";
export {
  InventoryItemsListByVmmServerOptionalParams,
  InventoryItemsDeleteOptionalParams,
  InventoryItemsCreateOptionalParams,
  InventoryItemsGetOptionalParams,
} from "./api/inventoryItems/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  VirtualMachineInstancesRestoreCheckpointOptionalParams,
  VirtualMachineInstancesDeleteCheckpointOptionalParams,
  VirtualMachineInstancesCreateCheckpointOptionalParams,
  VirtualMachineInstancesRestartOptionalParams,
  VirtualMachineInstancesStartOptionalParams,
  VirtualMachineInstancesStopOptionalParams,
  VirtualMachineInstancesListOptionalParams,
  VirtualMachineInstancesDeleteOptionalParams,
  VirtualMachineInstancesUpdateOptionalParams,
  VirtualMachineInstancesCreateOrUpdateOptionalParams,
  VirtualMachineInstancesGetOptionalParams,
} from "./api/virtualMachineInstances/index.js";
export {
  VirtualMachineTemplatesListBySubscriptionOptionalParams,
  VirtualMachineTemplatesListByResourceGroupOptionalParams,
  VirtualMachineTemplatesDeleteOptionalParams,
  VirtualMachineTemplatesUpdateOptionalParams,
  VirtualMachineTemplatesCreateOrUpdateOptionalParams,
  VirtualMachineTemplatesGetOptionalParams,
} from "./api/virtualMachineTemplates/index.js";
export {
  VirtualNetworksListBySubscriptionOptionalParams,
  VirtualNetworksListByResourceGroupOptionalParams,
  VirtualNetworksDeleteOptionalParams,
  VirtualNetworksUpdateOptionalParams,
  VirtualNetworksCreateOrUpdateOptionalParams,
  VirtualNetworksGetOptionalParams,
} from "./api/virtualNetworks/index.js";
export {
  VmInstanceHybridIdentityMetadatasListByVirtualMachineInstanceOptionalParams,
  VmInstanceHybridIdentityMetadatasGetOptionalParams,
} from "./api/vmInstanceHybridIdentityMetadatas/index.js";
export {
  VmmServersListBySubscriptionOptionalParams,
  VmmServersListByResourceGroupOptionalParams,
  VmmServersDeleteOptionalParams,
  VmmServersUpdateOptionalParams,
  VmmServersCreateOrUpdateOptionalParams,
  VmmServersGetOptionalParams,
} from "./api/vmmServers/index.js";
export {
  AvailabilitySetsOperations,
  CloudsOperations,
  GuestAgentsOperations,
  InventoryItemsOperations,
  OperationsOperations,
  VirtualMachineInstancesOperations,
  VirtualMachineTemplatesOperations,
  VirtualNetworksOperations,
  VmInstanceHybridIdentityMetadatasOperations,
  VmmServersOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
