// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { Client } from "./client.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  WorkloadNetwork,
  WorkloadNetworkProperties,
  KnownWorkloadNetworkProvisioningState,
  WorkloadNetworkProvisioningState,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  WorkloadNetworkDhcp,
  WorkloadNetworkDhcpEntity,
  WorkloadNetworkDhcpEntityUnion,
  KnownDhcpTypeEnum,
  DhcpTypeEnum,
  KnownWorkloadNetworkDhcpProvisioningState,
  WorkloadNetworkDhcpProvisioningState,
  WorkloadNetworkDhcpServer,
  WorkloadNetworkDhcpRelay,
  WorkloadNetworkDnsService,
  WorkloadNetworkDnsServiceProperties,
  KnownDnsServiceLogLevelEnum,
  DnsServiceLogLevelEnum,
  KnownDnsServiceStatusEnum,
  DnsServiceStatusEnum,
  KnownWorkloadNetworkDnsServiceProvisioningState,
  WorkloadNetworkDnsServiceProvisioningState,
  WorkloadNetworkDnsZone,
  WorkloadNetworkDnsZoneProperties,
  KnownWorkloadNetworkDnsZoneProvisioningState,
  WorkloadNetworkDnsZoneProvisioningState,
  WorkloadNetworkGateway,
  WorkloadNetworkGatewayProperties,
  WorkloadNetworkPortMirroring,
  WorkloadNetworkPortMirroringProperties,
  KnownPortMirroringDirectionEnum,
  PortMirroringDirectionEnum,
  KnownPortMirroringStatusEnum,
  PortMirroringStatusEnum,
  KnownWorkloadNetworkPortMirroringProvisioningState,
  WorkloadNetworkPortMirroringProvisioningState,
  WorkloadNetworkPublicIP,
  WorkloadNetworkPublicIPProperties,
  KnownWorkloadNetworkPublicIPProvisioningState,
  WorkloadNetworkPublicIPProvisioningState,
  WorkloadNetworkSegment,
  WorkloadNetworkSegmentProperties,
  WorkloadNetworkSegmentSubnet,
  WorkloadNetworkSegmentPortVif,
  KnownSegmentStatusEnum,
  SegmentStatusEnum,
  KnownWorkloadNetworkSegmentProvisioningState,
  WorkloadNetworkSegmentProvisioningState,
  WorkloadNetworkVirtualMachine,
  WorkloadNetworkVirtualMachineProperties,
  KnownVMTypeEnum,
  VMTypeEnum,
  WorkloadNetworkVMGroup,
  WorkloadNetworkVMGroupProperties,
  KnownVMGroupStatusEnum,
  VMGroupStatusEnum,
  KnownWorkloadNetworkVMGroupProvisioningState,
  WorkloadNetworkVMGroupProvisioningState,
  KnownVersions,
} from "./models/index.js";
export { ClientOptionalParams } from "./api/index.js";
export {
  WorkloadNetworksClientDeleteVMGroupOptionalParams,
  WorkloadNetworksClientUpdateVMGroupOptionalParams,
  WorkloadNetworksClientCreateVMGroupOptionalParams,
  WorkloadNetworksClientGetVMGroupOptionalParams,
  WorkloadNetworksClientListVMGropusOptionalParams,
  WorkloadNetworksClientGetVirtualMachineOptionalParams,
  WorkloadNetworksClientListVirtualMachinesOptionalParams,
  WorkloadNetworksClientDeleteSegmentOptionalParams,
  WorkloadNetworksClientUpdateSegmentOptionalParams,
  WorkloadNetworksClientCreateSegmentOptionalParams,
  WorkloadNetworksClientGetSegmentOptionalParams,
  WorkloadNetworksClientListSegmentsOptionalParams,
  WorkloadNetworksClientDeletePublicIPOptionalParams,
  WorkloadNetworksClientCreatePublicIPOptionalParams,
  WorkloadNetworksClientGetPublicIPOptionalParams,
  WorkloadNetworksClientListPublicIPsOptionalParams,
  WorkloadNetworksClientDeletePortMirroringOptionalParams,
  WorkloadNetworksClientUpdatePortMirroringOptionalParams,
  WorkloadNetworksClientCreatePortMirroringOptionalParams,
  WorkloadNetworksClientGetPortMirroringOptionalParams,
  WorkloadNetworksClientListPortMirroringOptionalParams,
  WorkloadNetworksClientGetGatewayOptionalParams,
  WorkloadNetworksClientListGatewaysOptionalParams,
  WorkloadNetworksClientDeleteDnsZoneOptionalParams,
  WorkloadNetworksClientUpdateDnsZoneOptionalParams,
  WorkloadNetworksClientCreateDnsZoneOptionalParams,
  WorkloadNetworksClientGetDnsZoneOptionalParams,
  WorkloadNetworksClientListDnsZonesOptionalParams,
  WorkloadNetworksClientDeleteDnsServiceOptionalParams,
  WorkloadNetworksClientUpdateDnsServiceOptionalParams,
  WorkloadNetworksClientCreateDnsServiceOptionalParams,
  WorkloadNetworksClientGetDnsServiceOptionalParams,
  WorkloadNetworksClientListDnsServiceOptionalParams,
  WorkloadNetworksClientDeleteDhcpOptionalParams,
  WorkloadNetworksClientUpdateDhcpOptionalParams,
  WorkloadNetworksClientCreateDhcpOptionalParams,
  WorkloadNetworksClientGetDhcpOptionalParams,
  WorkloadNetworksClientListDhcpOptionalParams,
  WorkloadNetworksClientGetOptionalParams,
  WorkloadNetworksClientListOptionalParams,
} from "./api/workloadNetworksClient/index.js";
export { WorkloadNetworksClientOperations } from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
