// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { DevOpsInfrastructureClient } from "./devOpsInfrastructureClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  Pool,
  PoolProperties,
  KnownProvisioningState,
  ProvisioningState,
  OrganizationProfile,
  OrganizationProfileUnion,
  GitHubOrganizationProfile,
  GitHubOrganization,
  AzureDevOpsOrganizationProfile,
  Organization,
  AzureDevOpsPermissionProfile,
  KnownAzureDevOpsPermissionType,
  AzureDevOpsPermissionType,
  AgentProfile,
  AgentProfileUnion,
  ResourcePredictions,
  ResourcePredictionsProfile,
  ResourcePredictionsProfileUnion,
  KnownResourcePredictionsProfileType,
  ResourcePredictionsProfileType,
  ManualResourcePredictionsProfile,
  AutomaticResourcePredictionsProfile,
  KnownPredictionPreference,
  PredictionPreference,
  StatelessAgentProfile,
  Stateful,
  FabricProfile,
  FabricProfileUnion,
  VmssFabricProfile,
  DevOpsAzureSku,
  PoolImage,
  KnownEphemeralType,
  EphemeralType,
  OsProfile,
  SecretsManagementSettings,
  KnownCertificateStoreNameOption,
  CertificateStoreNameOption,
  KnownLogonType,
  LogonType,
  StorageProfile,
  KnownOsDiskStorageAccountType,
  OsDiskStorageAccountType,
  DataDisk,
  KnownCachingType,
  CachingType,
  KnownStorageAccountType,
  StorageAccountType,
  NetworkProfile,
  ManagedServiceIdentity,
  KnownManagedServiceIdentityType,
  ManagedServiceIdentityType,
  UserAssignedIdentity,
  TrackedResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  PoolUpdate,
  PoolUpdateProperties,
  CheckNameAvailability,
  KnownDevOpsInfrastructureResourceType,
  DevOpsInfrastructureResourceType,
  CheckNameAvailabilityResult,
  KnownAvailabilityStatus,
  AvailabilityStatus,
  KnownCheckNameAvailabilityReason,
  CheckNameAvailabilityReason,
  ResourceDetailsObject,
  ResourceDetailsObjectProperties,
  KnownResourceStatus,
  ResourceStatus,
  ProxyResource,
  ResourceSku,
  ResourceSkuProperties,
  ResourceSkuLocationInfo,
  ResourceSkuZoneDetails,
  ResourceSkuCapabilities,
  ResourceSkuRestrictions,
  KnownResourceSkuRestrictionsType,
  ResourceSkuRestrictionsType,
  ResourceSkuRestrictionInfo,
  KnownResourceSkuRestrictionsReasonCode,
  ResourceSkuRestrictionsReasonCode,
  Quota,
  QuotaName,
  ImageVersion,
  ImageVersionProperties,
  KnownVersions,
} from "./models/index.js";
export { DevOpsInfrastructureClientOptionalParams } from "./api/index.js";
export { ImageVersionsListByImageOptionalParams } from "./api/imageVersions/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  PoolsCheckNameAvailabilityOptionalParams,
  PoolsListBySubscriptionOptionalParams,
  PoolsListByResourceGroupOptionalParams,
  PoolsDeleteOptionalParams,
  PoolsUpdateOptionalParams,
  PoolsCreateOrUpdateOptionalParams,
  PoolsGetOptionalParams,
} from "./api/pools/index.js";
export { ResourceDetailsListByPoolOptionalParams } from "./api/resourceDetails/index.js";
export { SkuListByLocationOptionalParams } from "./api/sku/index.js";
export { SubscriptionUsagesUsagesOptionalParams } from "./api/subscriptionUsages/index.js";
export {
  ImageVersionsOperations,
  OperationsOperations,
  PoolsOperations,
  ResourceDetailsOperations,
  SkuOperations,
  SubscriptionUsagesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
