# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/healthdataaiservices
    exclude:
      - sdk/healthdataaiservices/arm-healthdataaiservices
      - sdk/healthdataaiservices/ci.mgmt.yml
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/healthdataaiservices
    exclude:
      - sdk/healthdataaiservices/arm-healthdataaiservices
      - sdk/healthdataaiservices/ci.mgmt.yml
parameters:
  - name: oneESTemplateTag
    type: string
    default: release
    values:
      - release
      - canary
extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    oneESTemplateTag: ${{ parameters.oneESTemplateTag }}
    ServiceDirectory: healthdataaiservices
    Artifacts:
      - name: azure-rest-health-deidentification
        safeName: azureresthealthdeidentification
