// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { ElasticSanClient } from "./elasticSanClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  ElasticSan,
  ElasticSanProperties,
  Sku,
  KnownSkuName,
  SkuName,
  KnownSkuTier,
  SkuTier,
  KnownProvisioningStates,
  ProvisioningStates,
  PrivateEndpointConnection,
  PrivateEndpointConnectionProperties,
  PrivateEndpoint,
  PrivateLinkServiceConnectionState,
  KnownPrivateEndpointServiceConnectionStatus,
  PrivateEndpointServiceConnectionStatus,
  KnownPublicNetworkAccess,
  PublicNetworkAccess,
  AutoScaleProperties,
  ScaleUpProperties,
  KnownAutoScalePolicyEnforcement,
  AutoScalePolicyEnforcement,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  TrackedResource,
  ElasticSanUpdate,
  ElasticSanUpdateProperties,
  PrivateLinkResource,
  PrivateLinkResourceProperties,
  VolumeGroup,
  Identity,
  KnownIdentityType,
  IdentityType,
  UserAssignedIdentity,
  VolumeGroupProperties,
  KnownStorageTargetType,
  StorageTargetType,
  KnownEncryptionType,
  EncryptionType,
  EncryptionProperties,
  KeyVaultProperties,
  EncryptionIdentity,
  NetworkRuleSet,
  VirtualNetworkRule,
  KnownAction,
  Action,
  DeleteRetentionPolicy,
  KnownPolicyState,
  PolicyState,
  VolumeGroupUpdate,
  VolumeGroupUpdateProperties,
  VolumeNameList,
  PreValidationResponse,
  DiskSnapshotList,
  Volume,
  VolumeProperties,
  SourceCreationData,
  KnownVolumeCreateOption,
  VolumeCreateOption,
  IscsiTargetInfo,
  KnownOperationalStatus,
  OperationalStatus,
  ManagedByInfo,
  VolumeUpdate,
  VolumeUpdateProperties,
  Snapshot,
  SnapshotProperties,
  SnapshotCreationData,
  SkuInformation,
  SkuLocationInfo,
  SKUCapability,
  KnownXMsAccessSoftDeletedResources,
  XMsAccessSoftDeletedResources,
  KnownXMsDeleteSnapshots,
  XMsDeleteSnapshots,
  KnownXMsForceDelete,
  XMsForceDelete,
  KnownDeleteType,
  DeleteType,
  KnownVersions,
} from "./models/index.js";
export { ElasticSanClientOptionalParams } from "./api/index.js";
export {
  ElasticSansListByElasticSanOptionalParams,
  ElasticSansListBySubscriptionOptionalParams,
  ElasticSansListByResourceGroupOptionalParams,
  ElasticSansDeleteOptionalParams,
  ElasticSansUpdateOptionalParams,
  ElasticSansCreateOptionalParams,
  ElasticSansGetOptionalParams,
} from "./api/elasticSans/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  PrivateEndpointConnectionsListOptionalParams,
  PrivateEndpointConnectionsDeleteOptionalParams,
  PrivateEndpointConnectionsCreateOptionalParams,
  PrivateEndpointConnectionsGetOptionalParams,
} from "./api/privateEndpointConnections/index.js";
export { SkusOperationGroupListOptionalParams } from "./api/skusOperationGroup/index.js";
export {
  SnapshotsListByVolumeGroupOptionalParams,
  SnapshotsDeleteOptionalParams,
  SnapshotsCreateOptionalParams,
  SnapshotsGetOptionalParams,
} from "./api/snapshots/index.js";
export {
  VolumeGroupsPreRestoreOptionalParams,
  VolumeGroupsPreBackupOptionalParams,
  VolumeGroupsListByElasticSanOptionalParams,
  VolumeGroupsDeleteOptionalParams,
  VolumeGroupsUpdateOptionalParams,
  VolumeGroupsCreateOptionalParams,
  VolumeGroupsGetOptionalParams,
} from "./api/volumeGroups/index.js";
export {
  VolumesRestoreVolumeOptionalParams,
  VolumesListByVolumeGroupOptionalParams,
  VolumesDeleteOptionalParams,
  VolumesUpdateOptionalParams,
  VolumesCreateOptionalParams,
  VolumesGetOptionalParams,
} from "./api/volumes/index.js";
export {
  ElasticSansOperations,
  OperationsOperations,
  PrivateEndpointConnectionsOperations,
  SkusOperationGroupOperations,
  SnapshotsOperations,
  VolumeGroupsOperations,
  VolumesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
