/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  DevOpsPolicyAssignment,
  DevOpsPolicyAssignmentsListOptionalParams,
  DevOpsPolicyAssignmentsGetOptionalParams,
  DevOpsPolicyAssignmentsGetResponse,
  DevOpsPolicyAssignmentsCreateOrUpdateOptionalParams,
  DevOpsPolicyAssignmentsCreateOrUpdateResponse,
  DevOpsPolicyAssignmentsUpdateOptionalParams,
  DevOpsPolicyAssignmentsUpdateResponse,
  DevOpsPolicyAssignmentsDeleteOptionalParams,
} from "../models/index.js";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a DevOpsPolicyAssignments. */
export interface DevOpsPolicyAssignments {
  /**
   * Returns a list of DevOps Policy Assignments.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param options The options parameters.
   */
  list(
    resourceGroupName: string,
    securityConnectorName: string,
    options?: DevOpsPolicyAssignmentsListOptionalParams,
  ): PagedAsyncIterableIterator<DevOpsPolicyAssignment>;
  /**
   * Returns a DevOps Policy Assignment Resource.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param policyAssignmentId The policy assignment Id.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    securityConnectorName: string,
    policyAssignmentId: string,
    options?: DevOpsPolicyAssignmentsGetOptionalParams,
  ): Promise<DevOpsPolicyAssignmentsGetResponse>;
  /**
   * Creates or updates a DevOps Policy Assignment Resource.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param policyAssignmentId The policy assignment Id.
   * @param devOpsPolicyAssignment The DevOps Policy Assignment.
   * @param options The options parameters.
   */
  beginCreateOrUpdate(
    resourceGroupName: string,
    securityConnectorName: string,
    policyAssignmentId: string,
    devOpsPolicyAssignment: DevOpsPolicyAssignment,
    options?: DevOpsPolicyAssignmentsCreateOrUpdateOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<DevOpsPolicyAssignmentsCreateOrUpdateResponse>,
      DevOpsPolicyAssignmentsCreateOrUpdateResponse
    >
  >;
  /**
   * Creates or updates a DevOps Policy Assignment Resource.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param policyAssignmentId The policy assignment Id.
   * @param devOpsPolicyAssignment The DevOps Policy Assignment.
   * @param options The options parameters.
   */
  beginCreateOrUpdateAndWait(
    resourceGroupName: string,
    securityConnectorName: string,
    policyAssignmentId: string,
    devOpsPolicyAssignment: DevOpsPolicyAssignment,
    options?: DevOpsPolicyAssignmentsCreateOrUpdateOptionalParams,
  ): Promise<DevOpsPolicyAssignmentsCreateOrUpdateResponse>;
  /**
   * Updates a DevOps Policy Assignment Resource.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param policyAssignmentId The policy assignment Id.
   * @param devOpsPolicyAssignment The DevOps Policy Assignment.
   * @param options The options parameters.
   */
  beginUpdate(
    resourceGroupName: string,
    securityConnectorName: string,
    policyAssignmentId: string,
    devOpsPolicyAssignment: DevOpsPolicyAssignment,
    options?: DevOpsPolicyAssignmentsUpdateOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<DevOpsPolicyAssignmentsUpdateResponse>,
      DevOpsPolicyAssignmentsUpdateResponse
    >
  >;
  /**
   * Updates a DevOps Policy Assignment Resource.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param policyAssignmentId The policy assignment Id.
   * @param devOpsPolicyAssignment The DevOps Policy Assignment.
   * @param options The options parameters.
   */
  beginUpdateAndWait(
    resourceGroupName: string,
    securityConnectorName: string,
    policyAssignmentId: string,
    devOpsPolicyAssignment: DevOpsPolicyAssignment,
    options?: DevOpsPolicyAssignmentsUpdateOptionalParams,
  ): Promise<DevOpsPolicyAssignmentsUpdateResponse>;
  /**
   * Deletes a DevOps Policy Assignment Resource.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param policyAssignmentId The policy assignment Id.
   * @param options The options parameters.
   */
  beginDelete(
    resourceGroupName: string,
    securityConnectorName: string,
    policyAssignmentId: string,
    options?: DevOpsPolicyAssignmentsDeleteOptionalParams,
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Deletes a DevOps Policy Assignment Resource.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param securityConnectorName The security connector name.
   * @param policyAssignmentId The policy assignment Id.
   * @param options The options parameters.
   */
  beginDeleteAndWait(
    resourceGroupName: string,
    securityConnectorName: string,
    policyAssignmentId: string,
    options?: DevOpsPolicyAssignmentsDeleteOptionalParams,
  ): Promise<void>;
}
