/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PollerLike, PollOperationState } from "@azure/core-lro";
import {
  SnapshotGetOptionalParams,
  SnapshotGetResponse,
  DownloadType,
  SnapshotDownloadOptionalParams,
  SnapshotDownloadResponse
} from "../models";

/** Interface representing a Snapshot. */
export interface Snapshot {
  /**
   * Get the AppComplianceAutomation snapshot and its properties.
   * @param reportName Report Name.
   * @param snapshotName Snapshot Name.
   * @param options The options parameters.
   */
  get(
    reportName: string,
    snapshotName: string,
    options?: SnapshotGetOptionalParams
  ): Promise<SnapshotGetResponse>;
  /**
   * Download compliance needs from snapshot, like: Compliance Report, Resource List.
   * @param reportName Report Name.
   * @param snapshotName Snapshot Name.
   * @param downloadType Indicates the download type.
   * @param options The options parameters.
   */
  beginDownload(
    reportName: string,
    snapshotName: string,
    downloadType: DownloadType,
    options?: SnapshotDownloadOptionalParams
  ): Promise<
    PollerLike<
      PollOperationState<SnapshotDownloadResponse>,
      SnapshotDownloadResponse
    >
  >;
  /**
   * Download compliance needs from snapshot, like: Compliance Report, Resource List.
   * @param reportName Report Name.
   * @param snapshotName Snapshot Name.
   * @param downloadType Indicates the download type.
   * @param options The options parameters.
   */
  beginDownloadAndWait(
    reportName: string,
    snapshotName: string,
    downloadType: DownloadType,
    options?: SnapshotDownloadOptionalParams
  ): Promise<SnapshotDownloadResponse>;
}
