/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  PackageResource,
  PackagesListByTestBaseAccountOptionalParams
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a Packages. */
export interface Packages {
  /**
   * Lists all the packages under a Test Base Account.
   * @param resourceGroupName The name of the resource group that contains the resource.
   * @param testBaseAccountName The resource name of the Test Base Account.
   * @param options The options parameters.
   */
  listByTestBaseAccount(
    resourceGroupName: string,
    testBaseAccountName: string,
    options?: PackagesListByTestBaseAccountOptionalParams
  ): PagedAsyncIterableIterator<PackageResource>;
}
