/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  TestBaseAccountFlightingRingGetOptionalParams,
  TestBaseAccountFlightingRingGetResponse
} from "../models";

/** Interface representing a TestBaseAccountFlightingRing. */
export interface TestBaseAccountFlightingRing {
  /**
   * Gets a flighting ring of a Test Base Account.
   * @param resourceGroupName The name of the resource group that contains the resource.
   * @param testBaseAccountName The resource name of the Test Base Account.
   * @param flightingRingResourceName The resource name of a flighting ring.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    testBaseAccountName: string,
    flightingRingResourceName: string,
    options?: TestBaseAccountFlightingRingGetOptionalParams
  ): Promise<TestBaseAccountFlightingRingGetResponse>;
}
