/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  VHDResource,
  VHDsListByTestBaseAccountOptionalParams,
  VHDsDeleteOptionalParams,
  VHDsGetOptionalParams,
  VHDsGetResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a VHDs. */
export interface VHDs {
  /**
   * Lists all the VHDs under a test base account.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param testBaseAccountName The resource name of the Test Base Account.
   * @param options The options parameters.
   */
  listByTestBaseAccount(
    resourceGroupName: string,
    testBaseAccountName: string,
    options?: VHDsListByTestBaseAccountOptionalParams
  ): PagedAsyncIterableIterator<VHDResource>;
  /**
   * Deletes a Test Base VHD.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param testBaseAccountName The resource name of the Test Base Account.
   * @param vhdName The resource name of the Test Base VHD.
   * @param options The options parameters.
   */
  delete(
    resourceGroupName: string,
    testBaseAccountName: string,
    vhdName: string,
    options?: VHDsDeleteOptionalParams
  ): Promise<void>;
  /**
   * Gets a Test Base VHD.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param testBaseAccountName The resource name of the Test Base Account.
   * @param vhdName The resource name of the Test Base VHD.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    testBaseAccountName: string,
    vhdName: string,
    options?: VHDsGetOptionalParams
  ): Promise<VHDsGetResponse>;
}
