// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { AstroClient } from "./astroClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  OrganizationResource,
  OrganizationProperties,
  MarketplaceDetails,
  KnownMarketplaceSubscriptionStatus,
  MarketplaceSubscriptionStatus,
  OfferDetails,
  KnownRenewalMode,
  RenewalMode,
  UserDetails,
  KnownResourceProvisioningState,
  ResourceProvisioningState,
  PartnerOrganizationProperties,
  SingleSignOnProperties,
  KnownSingleSignOnStates,
  SingleSignOnStates,
  ManagedServiceIdentityV4,
  KnownManagedServiceIdentityType,
  ManagedServiceIdentityType,
  UserAssignedIdentity,
  TrackedResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  OrganizationResourceUpdate,
  OrganizationResourceUpdateProperties,
  GetUsersRequest,
  PageInfo,
  GetUsersSuccessResponse,
  User,
  Role,
  GetRolesRequest,
  GetRolesSuccessResponse,
  GetResourcesRequest,
  GetResourcesSuccessResponse,
  PartnerResource,
  ManageRolesModel,
  RemoveUserRequest,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  KnownVersions,
} from "./models/index.js";
export {
  AstroClientOptionalParams,
  OperationsListOptionalParams,
  OrganizationsGetOptionalParams,
  OrganizationsCreateOrUpdateOptionalParams,
  OrganizationsUpdateOptionalParams,
  OrganizationsDeleteOptionalParams,
  OrganizationsListByResourceGroupOptionalParams,
  OrganizationsListBySubscriptionOptionalParams,
  OrganizationsGetUsersOptionalParams,
  OrganizationsGetRolesOptionalParams,
  OrganizationsGetResourcesOptionalParams,
  OrganizationsManageRolesOptionalParams,
  OrganizationsRemoveUserOptionalParams,
} from "./api/index.js";
export {
  OperationsOperations,
  OrganizationsOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
