// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { WorkloadsClient } from "./workloadsClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  AlertTemplate,
  AlertTemplateProperties,
  ErrorDetail,
  ErrorAdditionalInfo,
  KnownWorkloadMonitorProvisioningState,
  WorkloadMonitorProvisioningState,
  KnownConditionalOperator,
  ConditionalOperator,
  KnownDefaultThresholdInputOption,
  DefaultThresholdInputOption,
  AlertTemplateMetricMeasurement,
  KnownAlertTemplateMetricTriggerType,
  AlertTemplateMetricTriggerType,
  AlertTemplateQueryInputParameter,
  KnownAlertTemplateParameterType,
  AlertTemplateParameterType,
  KnownAlertTemplateSelectionMode,
  AlertTemplateSelectionMode,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  Alert,
  AlertProperties,
  AlertRuleProperties,
  KnownAlertRuleStatus,
  AlertRuleStatus,
  KnownAlertAutoMitigate,
  AlertAutoMitigate,
  AlertQueryParameter,
  SapLandscapeMonitorResource,
  SapLandscapeMonitorProperties,
  KnownSapLandscapeMonitorProvisioningState,
  SapLandscapeMonitorProvisioningState,
  SapLandscapeMonitorPropertiesGrouping,
  SapLandscapeMonitorSidMapping,
  SapLandscapeMonitorMetricThresholds,
  ProviderInstance,
  ProviderInstanceProperties,
  Health,
  KnownWorkloadProviderInstanceHealthState,
  WorkloadProviderInstanceHealthState,
  ProviderSpecificProperties,
  ProviderSpecificPropertiesUnion,
  HanaDbProviderInstanceProperties,
  KnownSslPreference,
  SslPreference,
  SapNetWeaverProviderInstanceProperties,
  PrometheusOsProviderInstanceProperties,
  Db2ProviderInstanceProperties,
  PrometheusHaClusterProviderInstanceProperties,
  MsSqlServerProviderInstanceProperties,
  OracleProviderInstanceProperties,
  Monitor,
  MonitorProperties,
  KnownRoutingPreference,
  RoutingPreference,
  ManagedResourceGroupConfiguration,
  AppServicePlanConfiguration,
  KnownAppServicePlanTier,
  AppServicePlanTier,
  ManagedServiceIdentity,
  KnownManagedServiceIdentityType,
  ManagedServiceIdentityType,
  UserAssignedIdentity,
  TrackedResource,
  UpdateMonitorRequest,
  KnownVersions,
} from "./models/index.js";
export {
  AlertTemplatesListOptionalParams,
  AlertTemplatesGetOptionalParams,
  AlertsListOptionalParams,
  AlertsDeleteOptionalParams,
  AlertsCreateOptionalParams,
  AlertsGetOptionalParams,
  SapLandscapeMonitorListByMonitorOptionalParams,
  SapLandscapeMonitorDeleteOptionalParams,
  SapLandscapeMonitorUpdateOptionalParams,
  SapLandscapeMonitorCreateOptionalParams,
  SapLandscapeMonitorGetOptionalParams,
  ProviderInstancesListByMonitorOptionalParams,
  ProviderInstancesDeleteOptionalParams,
  ProviderInstancesCreateOptionalParams,
  ProviderInstancesGetOptionalParams,
  MonitorsListOptionalParams,
  MonitorsListByResourceGroupOptionalParams,
  MonitorsDeleteOptionalParams,
  MonitorsUpdateOptionalParams,
  MonitorsCreateOptionalParams,
  MonitorsGetOptionalParams,
  WorkloadsClientOptionalParams,
} from "./api/index.js";
export {
  AlertsOperations,
  AlertTemplatesOperations,
  MonitorsOperations,
  ProviderInstancesOperations,
  SapLandscapeMonitorOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
