/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  AKSAssessment,
  AksAssessmentOperationsListByAssessmentProjectOptionalParams,
  AksAssessmentOperationsGetOptionalParams,
  AksAssessmentOperationsGetResponse,
  AksAssessmentOperationsCreateOptionalParams,
  AksAssessmentOperationsCreateResponse,
  AksAssessmentOperationsDeleteOptionalParams,
  AksAssessmentOperationsDownloadUrlOptionalParams,
  AksAssessmentOperationsDownloadUrlResponse,
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a AksAssessmentOperations. */
export interface AksAssessmentOperations {
  /**
   * List AKSAssessment resources by AssessmentProject
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param projectName Assessment Project Name
   * @param options The options parameters.
   */
  listByAssessmentProject(
    resourceGroupName: string,
    projectName: string,
    options?: AksAssessmentOperationsListByAssessmentProjectOptionalParams,
  ): PagedAsyncIterableIterator<AKSAssessment>;
  /**
   * Get a AKSAssessment
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param projectName Assessment Project Name
   * @param assessmentName AKS Assessment Name.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    projectName: string,
    assessmentName: string,
    options?: AksAssessmentOperationsGetOptionalParams,
  ): Promise<AksAssessmentOperationsGetResponse>;
  /**
   * Create a AKSAssessment
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param projectName Assessment Project Name
   * @param assessmentName AKS Assessment Name.
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  beginCreate(
    resourceGroupName: string,
    projectName: string,
    assessmentName: string,
    resource: AKSAssessment,
    options?: AksAssessmentOperationsCreateOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<AksAssessmentOperationsCreateResponse>,
      AksAssessmentOperationsCreateResponse
    >
  >;
  /**
   * Create a AKSAssessment
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param projectName Assessment Project Name
   * @param assessmentName AKS Assessment Name.
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  beginCreateAndWait(
    resourceGroupName: string,
    projectName: string,
    assessmentName: string,
    resource: AKSAssessment,
    options?: AksAssessmentOperationsCreateOptionalParams,
  ): Promise<AksAssessmentOperationsCreateResponse>;
  /**
   * Delete a AKSAssessment
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param projectName Assessment Project Name
   * @param assessmentName AKS Assessment Name.
   * @param options The options parameters.
   */
  delete(
    resourceGroupName: string,
    projectName: string,
    assessmentName: string,
    options?: AksAssessmentOperationsDeleteOptionalParams,
  ): Promise<void>;
  /**
   * Get URL for downloading AKS Assessment Report.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param projectName Assessment Project Name
   * @param assessmentName AKS Assessment Name.
   * @param body The content of the action request
   * @param options The options parameters.
   */
  beginDownloadUrl(
    resourceGroupName: string,
    projectName: string,
    assessmentName: string,
    body: Record<string, unknown>,
    options?: AksAssessmentOperationsDownloadUrlOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<AksAssessmentOperationsDownloadUrlResponse>,
      AksAssessmentOperationsDownloadUrlResponse
    >
  >;
  /**
   * Get URL for downloading AKS Assessment Report.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param projectName Assessment Project Name
   * @param assessmentName AKS Assessment Name.
   * @param body The content of the action request
   * @param options The options parameters.
   */
  beginDownloadUrlAndWait(
    resourceGroupName: string,
    projectName: string,
    assessmentName: string,
    body: Record<string, unknown>,
    options?: AksAssessmentOperationsDownloadUrlOptionalParams,
  ): Promise<AksAssessmentOperationsDownloadUrlResponse>;
}
