/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  DiscoveryNlpRequest,
  DiscoverySolutionNLPDiscoverSolutionsOptionalParams,
  DiscoverySolutionNLPDiscoverSolutionsResponse,
  DiscoverySolutionNLPDiscoverSolutionsBySubscriptionOptionalParams,
  DiscoverySolutionNLPDiscoverSolutionsBySubscriptionResponse,
} from "../models/index.js";

/** Interface representing a DiscoverySolutionNLP. */
export interface DiscoverySolutionNLP {
  /**
   * Search for relevant Azure Diagnostics, Solutions and Troubleshooters using a natural language issue
   * summary.
   * @param discoverSolutionRequest The request body
   * @param options The options parameters.
   */
  discoverSolutions(
    discoverSolutionRequest: DiscoveryNlpRequest,
    options?: DiscoverySolutionNLPDiscoverSolutionsOptionalParams,
  ): Promise<DiscoverySolutionNLPDiscoverSolutionsResponse>;
  /**
   * Search for relevant Azure Diagnostics, Solutions and Troubleshooters using a natural language issue
   * summary and subscription.
   * @param discoverSolutionRequest The request body
   * @param options The options parameters.
   */
  discoverSolutionsBySubscription(
    discoverSolutionRequest: DiscoveryNlpRequest,
    options?: DiscoverySolutionNLPDiscoverSolutionsBySubscriptionOptionalParams,
  ): Promise<DiscoverySolutionNLPDiscoverSolutionsBySubscriptionResponse>;
}
