// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ProxyResource,
  SolutionTypeResource,
  SolutionTypeProperties,
  SolutionTypeSettingsProperties,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  InventoryResource,
  InventoryProperties,
  KnownCloudNativeType,
  CloudNativeType,
  KnownSolutionConfigurationStatus,
  SolutionConfigurationStatus,
  KnownResourceProvisioningState,
  ResourceProvisioningState,
  ExtensionResource,
  SolutionConfiguration,
  SolutionConfigurationProperties,
  SolutionSettings,
  OperationStatusResult,
  TrackedResource,
  PublicCloudConnector,
  PublicCloudConnectorProperties,
  AwsCloudProfile,
  KnownHostType,
  HostType,
  GenerateAwsTemplateRequest,
  SolutionTypeSettings,
  Versions,
} from "./models.js";
export {
  GenerateAwsTemplatePostOptionalParams,
  PublicCloudConnectorsGetOptionalParams,
  PublicCloudConnectorsCreateOrUpdateOptionalParams,
  PublicCloudConnectorsUpdateOptionalParams,
  PublicCloudConnectorsDeleteOptionalParams,
  PublicCloudConnectorsListByResourceGroupOptionalParams,
  PublicCloudConnectorsListBySubscriptionOptionalParams,
  PublicCloudConnectorsTestPermissionsOptionalParams,
  SolutionConfigurationsGetOptionalParams,
  SolutionConfigurationsCreateOrUpdateOptionalParams,
  SolutionConfigurationsUpdateOptionalParams,
  SolutionConfigurationsDeleteOptionalParams,
  SolutionConfigurationsListOptionalParams,
  SolutionConfigurationsSyncNowOptionalParams,
  InventoryGetOptionalParams,
  InventoryListBySolutionConfigurationOptionalParams,
  SolutionTypesGetOptionalParams,
  SolutionTypesListByResourceGroupOptionalParams,
  SolutionTypesListBySubscriptionOptionalParams,
} from "./options.js";
