// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  SolutionTypeResource,
  SolutionTypeProperties,
  SolutionTypeSettingsProperties,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  InventoryResource,
  InventoryProperties,
  KnownCloudNativeType,
  CloudNativeType,
  KnownSolutionConfigurationStatus,
  SolutionConfigurationStatus,
  KnownResourceProvisioningState,
  ResourceProvisioningState,
  SolutionConfiguration,
  SolutionConfigurationProperties,
  SolutionSettings,
  ExtensionResource,
  OperationStatusResult,
  PublicCloudConnector,
  PublicCloudConnectorProperties,
  AwsCloudProfile,
  KnownHostType,
  HostType,
  TrackedResource,
  GenerateAwsTemplateRequest,
  SolutionTypeSettings,
  KnownVersions,
} from "./models.js";
