// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { StandbyPoolManagementClient } from "./standbyPoolManagementClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  StandbyContainerGroupPoolRuntimeViewResource,
  StandbyContainerGroupPoolRuntimeViewResourceProperties,
  ContainerGroupInstanceCountSummary,
  PoolResourceStateCount,
  KnownProvisioningState,
  ProvisioningState,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  StandbyContainerGroupPoolResource,
  StandbyContainerGroupPoolResourceProperties,
  StandbyContainerGroupPoolElasticityProfile,
  KnownRefillPolicy,
  RefillPolicy,
  ContainerGroupProperties,
  ContainerGroupProfile,
  Subnet,
  TrackedResource,
  StandbyContainerGroupPoolResourceUpdate,
  StandbyContainerGroupPoolResourceUpdateProperties,
  StandbyVirtualMachinePoolRuntimeViewResource,
  StandbyVirtualMachinePoolRuntimeViewResourceProperties,
  VirtualMachineInstanceCountSummary,
  StandbyVirtualMachineResource,
  StandbyVirtualMachineResourceProperties,
  StandbyVirtualMachinePoolResource,
  StandbyVirtualMachinePoolResourceProperties,
  StandbyVirtualMachinePoolElasticityProfile,
  KnownVirtualMachineState,
  VirtualMachineState,
  StandbyVirtualMachinePoolResourceUpdate,
  StandbyVirtualMachinePoolResourceUpdateProperties,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  KnownVersions,
} from "./models/index.js";
export {
  OperationsListOptionalParams,
  StandbyVirtualMachinePoolsGetOptionalParams,
  StandbyVirtualMachinePoolsCreateOrUpdateOptionalParams,
  StandbyVirtualMachinePoolsDeleteOptionalParams,
  StandbyVirtualMachinePoolsUpdateOptionalParams,
  StandbyVirtualMachinePoolsListByResourceGroupOptionalParams,
  StandbyVirtualMachinePoolsListBySubscriptionOptionalParams,
  StandbyVirtualMachinesGetOptionalParams,
  StandbyVirtualMachinesListByStandbyVirtualMachinePoolResourceOptionalParams,
  StandbyVirtualMachinePoolRuntimeViewsGetOptionalParams,
  StandbyVirtualMachinePoolRuntimeViewsListByStandbyPoolOptionalParams,
  StandbyContainerGroupPoolsGetOptionalParams,
  StandbyContainerGroupPoolsCreateOrUpdateOptionalParams,
  StandbyContainerGroupPoolsDeleteOptionalParams,
  StandbyContainerGroupPoolsUpdateOptionalParams,
  StandbyContainerGroupPoolsListByResourceGroupOptionalParams,
  StandbyContainerGroupPoolsListBySubscriptionOptionalParams,
  StandbyContainerGroupPoolRuntimeViewsGetOptionalParams,
  StandbyContainerGroupPoolRuntimeViewsListByStandbyPoolOptionalParams,
  StandbyPoolManagementClientOptionalParams,
} from "./api/index.js";
export {
  OperationsOperations,
  StandbyContainerGroupPoolRuntimeViewsOperations,
  StandbyContainerGroupPoolsOperations,
  StandbyVirtualMachinePoolRuntimeViewsOperations,
  StandbyVirtualMachinePoolsOperations,
  StandbyVirtualMachinesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
