// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  createAvs,
  AvsContext,
  AvsClientOptionalParams,
} from "./avsContext.js";
export {
  OperationsListOptionalParams,
  LocationsCheckTrialAvailabilityOptionalParams,
  LocationsCheckQuotaAvailabilityOptionalParams,
  PrivateCloudsListOptionalParams,
  PrivateCloudsListInSubscriptionOptionalParams,
  PrivateCloudsGetOptionalParams,
  PrivateCloudsCreateOrUpdateOptionalParams,
  PrivateCloudsUpdateOptionalParams,
  PrivateCloudsDeleteOptionalParams,
  PrivateCloudsRotateVcenterPasswordOptionalParams,
  PrivateCloudsRotateNsxtPasswordOptionalParams,
  PrivateCloudsListAdminCredentialsOptionalParams,
  ClustersListOptionalParams,
  ClustersGetOptionalParams,
  ClustersCreateOrUpdateOptionalParams,
  ClustersUpdateOptionalParams,
  ClustersDeleteOptionalParams,
  ClustersListZonesOptionalParams,
  DatastoresListOptionalParams,
  DatastoresGetOptionalParams,
  DatastoresCreateOrUpdateOptionalParams,
  DatastoresDeleteOptionalParams,
  HcxEnterpriseSitesListOptionalParams,
  HcxEnterpriseSitesGetOptionalParams,
  HcxEnterpriseSitesCreateOrUpdateOptionalParams,
  HcxEnterpriseSitesDeleteOptionalParams,
  AuthorizationsListOptionalParams,
  AuthorizationsGetOptionalParams,
  AuthorizationsCreateOrUpdateOptionalParams,
  AuthorizationsDeleteOptionalParams,
  GlobalReachConnectionsListOptionalParams,
  GlobalReachConnectionsGetOptionalParams,
  GlobalReachConnectionsCreateOrUpdateOptionalParams,
  GlobalReachConnectionsDeleteOptionalParams,
  CloudLinksListOptionalParams,
  CloudLinksGetOptionalParams,
  CloudLinksCreateOrUpdateOptionalParams,
  CloudLinksDeleteOptionalParams,
  AddonsListOptionalParams,
  AddonsGetOptionalParams,
  AddonsCreateOrUpdateOptionalParams,
  AddonsDeleteOptionalParams,
  VirtualMachinesListOptionalParams,
  VirtualMachinesGetOptionalParams,
  VirtualMachinesRestrictMovementOptionalParams,
  PlacementPoliciesListOptionalParams,
  PlacementPoliciesGetOptionalParams,
  PlacementPoliciesCreateOrUpdateOptionalParams,
  PlacementPoliciesUpdateOptionalParams,
  PlacementPoliciesDeleteOptionalParams,
  ScriptPackagesListOptionalParams,
  ScriptPackagesGetOptionalParams,
  ScriptCmdletsListOptionalParams,
  ScriptCmdletsGetOptionalParams,
  ScriptExecutionsListOptionalParams,
  ScriptExecutionsGetOptionalParams,
  ScriptExecutionsCreateOrUpdateOptionalParams,
  ScriptExecutionsDeleteOptionalParams,
  ScriptExecutionsGetExecutionLogsOptionalParams,
  IscsiPathsListByPrivateCloudOptionalParams,
  IscsiPathsGetOptionalParams,
  IscsiPathsCreateOrUpdateOptionalParams,
  IscsiPathsDeleteOptionalParams,
  WorkloadNetworksListOptionalParams,
  WorkloadNetworksGetOptionalParams,
  WorkloadNetworksListSegmentsOptionalParams,
  WorkloadNetworksGetSegmentOptionalParams,
  WorkloadNetworksCreateSegmentOptionalParams,
  WorkloadNetworksUpdateSegmentOptionalParams,
  WorkloadNetworksDeleteSegmentOptionalParams,
  WorkloadNetworksListDhcpOptionalParams,
  WorkloadNetworksGetDhcpOptionalParams,
  WorkloadNetworksCreateDhcpOptionalParams,
  WorkloadNetworksUpdateDhcpOptionalParams,
  WorkloadNetworksDeleteDhcpOptionalParams,
  WorkloadNetworksListGatewaysOptionalParams,
  WorkloadNetworksGetGatewayOptionalParams,
  WorkloadNetworksListPortMirroringOptionalParams,
  WorkloadNetworksGetPortMirroringOptionalParams,
  WorkloadNetworksCreatePortMirroringOptionalParams,
  WorkloadNetworksUpdatePortMirroringOptionalParams,
  WorkloadNetworksDeletePortMirroringOptionalParams,
  WorkloadNetworksListVMGroupsOptionalParams,
  WorkloadNetworksGetVMGroupOptionalParams,
  WorkloadNetworksCreateVMGroupOptionalParams,
  WorkloadNetworksUpdateVMGroupOptionalParams,
  WorkloadNetworksDeleteVMGroupOptionalParams,
  WorkloadNetworksListVirtualMachinesOptionalParams,
  WorkloadNetworksGetVirtualMachineOptionalParams,
  WorkloadNetworksListDnsServicesOptionalParams,
  WorkloadNetworksGetDnsServiceOptionalParams,
  WorkloadNetworksCreateDnsServiceOptionalParams,
  WorkloadNetworksUpdateDnsServiceOptionalParams,
  WorkloadNetworksDeleteDnsServiceOptionalParams,
  WorkloadNetworksListDnsZonesOptionalParams,
  WorkloadNetworksGetDnsZoneOptionalParams,
  WorkloadNetworksCreateDnsZoneOptionalParams,
  WorkloadNetworksUpdateDnsZoneOptionalParams,
  WorkloadNetworksDeleteDnsZoneOptionalParams,
  WorkloadNetworksListPublicIPsOptionalParams,
  WorkloadNetworksGetPublicIPOptionalParams,
  WorkloadNetworksCreatePublicIPOptionalParams,
  WorkloadNetworksDeletePublicIPOptionalParams,
} from "./options.js";
export {
  addonsList,
  addonsGet,
  addonsCreateOrUpdate,
  addonsDelete,
} from "./addons/index.js";
export {
  authorizationsList,
  authorizationsGet,
  authorizationsCreateOrUpdate,
  authorizationsDelete,
} from "./authorizations/index.js";
export {
  cloudLinksList,
  cloudLinksGet,
  cloudLinksCreateOrUpdate,
  cloudLinksDelete,
} from "./cloudLinks/index.js";
export {
  clustersList,
  clustersGet,
  clustersCreateOrUpdate,
  clustersUpdate,
  clustersDelete,
  clustersListZones,
} from "./clusters/index.js";
export {
  datastoresList,
  datastoresGet,
  datastoresCreateOrUpdate,
  datastoresDelete,
} from "./datastores/index.js";
export {
  globalReachConnectionsList,
  globalReachConnectionsGet,
  globalReachConnectionsCreateOrUpdate,
  globalReachConnectionsDelete,
} from "./globalReachConnections/index.js";
export {
  hcxEnterpriseSitesList,
  hcxEnterpriseSitesGet,
  hcxEnterpriseSitesCreateOrUpdate,
  hcxEnterpriseSitesDelete,
} from "./hcxEnterpriseSites/index.js";
export {
  iscsiPathsListByPrivateCloud,
  iscsiPathsGet,
  iscsiPathsCreateOrUpdate,
  iscsiPathsDelete,
} from "./iscsiPaths/index.js";
export {
  locationsCheckTrialAvailability,
  locationsCheckQuotaAvailability,
} from "./locations/index.js";
export { operationsList } from "./operations/index.js";
export {
  placementPoliciesList,
  placementPoliciesGet,
  placementPoliciesCreateOrUpdate,
  placementPoliciesUpdate,
  placementPoliciesDelete,
} from "./placementPolicies/index.js";
export {
  privateCloudsList,
  privateCloudsListInSubscription,
  privateCloudsGet,
  privateCloudsCreateOrUpdate,
  privateCloudsUpdate,
  privateCloudsDelete,
  privateCloudsRotateVcenterPassword,
  privateCloudsRotateNsxtPassword,
  privateCloudsListAdminCredentials,
} from "./privateClouds/index.js";
export { scriptCmdletsList, scriptCmdletsGet } from "./scriptCmdlets/index.js";
export {
  scriptExecutionsList,
  scriptExecutionsGet,
  scriptExecutionsCreateOrUpdate,
  scriptExecutionsDelete,
  scriptExecutionsGetExecutionLogs,
} from "./scriptExecutions/index.js";
export {
  scriptPackagesList,
  scriptPackagesGet,
} from "./scriptPackages/index.js";
export {
  virtualMachinesList,
  virtualMachinesGet,
  virtualMachinesRestrictMovement,
} from "./virtualMachines/index.js";
export {
  workloadNetworksList,
  workloadNetworksGet,
  workloadNetworksListSegments,
  workloadNetworksGetSegment,
  workloadNetworksCreateSegment,
  workloadNetworksUpdateSegment,
  workloadNetworksDeleteSegment,
  workloadNetworksListDhcp,
  workloadNetworksGetDhcp,
  workloadNetworksCreateDhcp,
  workloadNetworksUpdateDhcp,
  workloadNetworksDeleteDhcp,
  workloadNetworksListGateways,
  workloadNetworksGetGateway,
  workloadNetworksListPortMirroring,
  workloadNetworksGetPortMirroring,
  workloadNetworksCreatePortMirroring,
  workloadNetworksUpdatePortMirroring,
  workloadNetworksDeletePortMirroring,
  workloadNetworksListVMGroups,
  workloadNetworksGetVMGroup,
  workloadNetworksCreateVMGroup,
  workloadNetworksUpdateVMGroup,
  workloadNetworksDeleteVMGroup,
  workloadNetworksListVirtualMachines,
  workloadNetworksGetVirtualMachine,
  workloadNetworksListDnsServices,
  workloadNetworksGetDnsService,
  workloadNetworksCreateDnsService,
  workloadNetworksUpdateDnsService,
  workloadNetworksDeleteDnsService,
  workloadNetworksListDnsZones,
  workloadNetworksGetDnsZone,
  workloadNetworksCreateDnsZone,
  workloadNetworksUpdateDnsZone,
  workloadNetworksDeleteDnsZone,
  workloadNetworksListPublicIPs,
  workloadNetworksGetPublicIP,
  workloadNetworksCreatePublicIP,
  workloadNetworksDeletePublicIP,
} from "./workloadNetworks/index.js";
