# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/kubernetesconfiguration/ci.mgmt.yml
      - sdk/kubernetesconfiguration/arm-kubernetesconfiguration
      - sdk/kubernetesconfiguration/arm-kubernetesconfiguration-privatelinkscopes
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/kubernetesconfiguration/ci.mgmt.yml
      - sdk/kubernetesconfiguration/arm-kubernetesconfiguration
      - sdk/kubernetesconfiguration/arm-kubernetesconfiguration-privatelinkscopes
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: kubernetesconfiguration
    Artifacts:
      - name: azure-arm-kubernetesconfiguration
        safeName: azurearmkubernetesconfiguration
      - name: azure-arm-kubernetesconfiguration-privatelinkscopes
        safeName: azurearmkubernetesconfigurationprivatelinkscopes
