// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { DatabaseFleetManagerClient } from "./databaseFleetManagerClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  FleetTier,
  FleetTierProperties,
  KnownZoneRedundancy,
  ZoneRedundancy,
  KnownAzureProvisioningState,
  AzureProvisioningState,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  FirewallRule,
  FirewallRuleProperties,
  Fleet,
  FleetProperties,
  TrackedResource,
  FleetUpdate,
  Fleetspace,
  FleetspaceProperties,
  MainPrincipal,
  KnownPrincipalType,
  PrincipalType,
  RegisterServerProperties,
  DestinationTierOverride,
  KnownResourceType,
  ResourceType,
  FleetDatabase,
  FleetDatabaseProperties,
  KnownDatabaseCreateMode,
  DatabaseCreateMode,
  Identity,
  KnownIdentityType,
  IdentityType,
  DatabaseIdentity,
  TransparentDataEncryption,
  DatabaseChangeTierProperties,
  DatabaseRenameProperties,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  KnownVersions,
} from "./models/index.js";
export {
  DatabaseFleetManagerClientOptionalParams,
  FleetTiersDisableOptionalParams,
  FleetTiersListByFleetOptionalParams,
  FleetTiersDeleteOptionalParams,
  FleetTiersUpdateOptionalParams,
  FleetTiersCreateOrUpdateOptionalParams,
  FleetTiersGetOptionalParams,
  FirewallRulesListByFleetspaceOptionalParams,
  FirewallRulesDeleteOptionalParams,
  FirewallRulesCreateOrUpdateOptionalParams,
  FirewallRulesGetOptionalParams,
  FleetsListOptionalParams,
  FleetsListByResourceGroupOptionalParams,
  FleetsDeleteOptionalParams,
  FleetsUpdateOptionalParams,
  FleetsCreateOrUpdateOptionalParams,
  FleetsGetOptionalParams,
  FleetspacesUnregisterOptionalParams,
  FleetspacesRegisterServerOptionalParams,
  FleetspacesListByFleetOptionalParams,
  FleetspacesDeleteOptionalParams,
  FleetspacesUpdateOptionalParams,
  FleetspacesCreateOrUpdateOptionalParams,
  FleetspacesGetOptionalParams,
  FleetDatabasesRevertOptionalParams,
  FleetDatabasesRenameOptionalParams,
  FleetDatabasesChangeTierOptionalParams,
  FleetDatabasesListByFleetspaceOptionalParams,
  FleetDatabasesDeleteOptionalParams,
  FleetDatabasesUpdateOptionalParams,
  FleetDatabasesCreateOrUpdateOptionalParams,
  FleetDatabasesGetOptionalParams,
  OperationsListOptionalParams,
} from "./api/index.js";
export {
  FirewallRulesOperations,
  FleetDatabasesOperations,
  FleetsOperations,
  FleetspacesOperations,
  FleetTiersOperations,
  OperationsOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
