/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  ScalingPlanPersonalSchedule,
  ScalingPlanPersonalSchedulesListOptionalParams,
  ScalingPlanPersonalSchedulesGetOptionalParams,
  ScalingPlanPersonalSchedulesGetResponse,
  ScalingPlanPersonalSchedulesCreateOptionalParams,
  ScalingPlanPersonalSchedulesCreateResponse,
  ScalingPlanPersonalSchedulePatch,
  ScalingPlanPersonalSchedulesUpdateOptionalParams,
  ScalingPlanPersonalSchedulesUpdateResponse,
  ScalingPlanPersonalSchedulesDeleteOptionalParams,
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a ScalingPlanPersonalSchedules. */
export interface ScalingPlanPersonalSchedules {
  /**
   * List ScalingPlanPersonalSchedules.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param options The options parameters.
   */
  list(
    resourceGroupName: string,
    scalingPlanName: string,
    options?: ScalingPlanPersonalSchedulesListOptionalParams,
  ): PagedAsyncIterableIterator<ScalingPlanPersonalSchedule>;
  /**
   * Get a ScalingPlanPersonalSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    options?: ScalingPlanPersonalSchedulesGetOptionalParams,
  ): Promise<ScalingPlanPersonalSchedulesGetResponse>;
  /**
   * Create or update a ScalingPlanPersonalSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param resource Object containing ScalingPlanPersonalSchedule definitions.
   * @param options The options parameters.
   */
  create(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    resource: ScalingPlanPersonalSchedule,
    options?: ScalingPlanPersonalSchedulesCreateOptionalParams,
  ): Promise<ScalingPlanPersonalSchedulesCreateResponse>;
  /**
   * Update a ScalingPlanPersonalSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param properties Object containing ScalingPlanPersonalSchedule definitions.
   * @param options The options parameters.
   */
  update(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    properties: ScalingPlanPersonalSchedulePatch,
    options?: ScalingPlanPersonalSchedulesUpdateOptionalParams,
  ): Promise<ScalingPlanPersonalSchedulesUpdateResponse>;
  /**
   * Remove a ScalingPlanPersonalSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param options The options parameters.
   */
  delete(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    options?: ScalingPlanPersonalSchedulesDeleteOptionalParams,
  ): Promise<void>;
}
