/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  ScalingPlanPooledSchedule,
  ScalingPlanPooledSchedulesListOptionalParams,
  ScalingPlanPooledSchedulesGetOptionalParams,
  ScalingPlanPooledSchedulesGetResponse,
  ScalingPlanPooledSchedulesCreateOptionalParams,
  ScalingPlanPooledSchedulesCreateResponse,
  ScalingPlanPooledSchedulePatch,
  ScalingPlanPooledSchedulesUpdateOptionalParams,
  ScalingPlanPooledSchedulesUpdateResponse,
  ScalingPlanPooledSchedulesDeleteOptionalParams,
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a ScalingPlanPooledSchedules. */
export interface ScalingPlanPooledSchedules {
  /**
   * List ScalingPlanPooledSchedules.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param options The options parameters.
   */
  list(
    resourceGroupName: string,
    scalingPlanName: string,
    options?: ScalingPlanPooledSchedulesListOptionalParams,
  ): PagedAsyncIterableIterator<ScalingPlanPooledSchedule>;
  /**
   * Get a ScalingPlanPooledSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    options?: ScalingPlanPooledSchedulesGetOptionalParams,
  ): Promise<ScalingPlanPooledSchedulesGetResponse>;
  /**
   * Create or update a ScalingPlanPooledSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param resource Object containing ScalingPlanPooledSchedule definitions.
   * @param options The options parameters.
   */
  create(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    resource: ScalingPlanPooledSchedule,
    options?: ScalingPlanPooledSchedulesCreateOptionalParams,
  ): Promise<ScalingPlanPooledSchedulesCreateResponse>;
  /**
   * Update a ScalingPlanPooledSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param properties Object containing ScalingPlanPooledSchedule definitions.
   * @param options The options parameters.
   */
  update(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    properties: ScalingPlanPooledSchedulePatch,
    options?: ScalingPlanPooledSchedulesUpdateOptionalParams,
  ): Promise<ScalingPlanPooledSchedulesUpdateResponse>;
  /**
   * Remove a ScalingPlanPooledSchedule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param scalingPlanName The name of the scaling plan.
   * @param scalingPlanScheduleName The name of the ScalingPlanSchedule
   * @param options The options parameters.
   */
  delete(
    resourceGroupName: string,
    scalingPlanName: string,
    scalingPlanScheduleName: string,
    options?: ScalingPlanPooledSchedulesDeleteOptionalParams,
  ): Promise<void>;
}
