// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  StandbyContainerGroupPoolRuntimeViewResource,
  StandbyContainerGroupPoolRuntimeViewResourceProperties,
  ContainerGroupInstanceCountSummary,
  PoolResourceStateCount,
  KnownProvisioningState,
  ProvisioningState,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  StandbyContainerGroupPoolResource,
  StandbyContainerGroupPoolResourceProperties,
  StandbyContainerGroupPoolElasticityProfile,
  KnownRefillPolicy,
  RefillPolicy,
  ContainerGroupProperties,
  ContainerGroupProfile,
  Subnet,
  TrackedResource,
  StandbyContainerGroupPoolResourceUpdate,
  StandbyContainerGroupPoolResourceUpdateProperties,
  StandbyVirtualMachinePoolRuntimeViewResource,
  StandbyVirtualMachinePoolRuntimeViewResourceProperties,
  VirtualMachineInstanceCountSummary,
  StandbyVirtualMachineResource,
  StandbyVirtualMachineResourceProperties,
  StandbyVirtualMachinePoolResource,
  StandbyVirtualMachinePoolResourceProperties,
  StandbyVirtualMachinePoolElasticityProfile,
  KnownVirtualMachineState,
  VirtualMachineState,
  StandbyVirtualMachinePoolResourceUpdate,
  StandbyVirtualMachinePoolResourceUpdateProperties,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  KnownVersions,
} from "./models.js";
