# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/cognitiveservices/
    exclude:
      - sdk/cognitiveservices/ci.mgmt.yml
      - sdk/cognitiveservices/arm-cognitiveservices
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/cognitiveservices/
    exclude:
      - sdk/cognitiveservices/ci.mgmt.yml
      - sdk/cognitiveservices/arm-cognitiveservices
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: cognitiveservices
    Artifacts:
      - name: azure-rest-ai-speechtotext-batchtranscription
        safeName: azurerestaispeechtotextbatchtranscription
