/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  NodeConfigurationResources,
  NodeConfigurationsValidateOptionalParams
} from "../models";

/** Interface representing a NodeConfigurations. */
export interface NodeConfigurations {
  /**
   * Validate the Node Configuration Resources
   * @param resourceUri The fully qualified Azure Resource manager identifier of the resource to be
   *                    connected.
   * @param nodeConfigurationName The name of the node configuration resource
   * @param nodeConfigurationResources The list of node Configuration Resources.
   * @param options The options parameters.
   */
  validate(
    resourceUri: string,
    nodeConfigurationName: string,
    nodeConfigurationResources: NodeConfigurationResources,
    options?: NodeConfigurationsValidateOptionalParams
  ): Promise<void>;
}
