// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { HybridConnectivityManagementAPIClient } from "./hybridConnectivityManagementAPIClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  SolutionTypeResource,
  SolutionTypeProperties,
  SolutionTypeSettingsProperties,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorDetail,
  ErrorAdditionalInfo,
  InventoryResource,
  InventoryProperties,
  KnownCloudNativeType,
  CloudNativeType,
  KnownSolutionConfigurationStatus,
  SolutionConfigurationStatus,
  KnownResourceProvisioningState,
  ResourceProvisioningState,
  SolutionConfiguration,
  SolutionConfigurationProperties,
  SolutionSettings,
  ExtensionResource,
  OperationStatusResult,
  PublicCloudConnector,
  PublicCloudConnectorProperties,
  AwsCloudProfile,
  KnownHostType,
  HostType,
  TrackedResource,
  GenerateAwsTemplateRequest,
  SolutionTypeSettings,
  ServiceConfigurationResource,
  ServiceConfigurationProperties,
  KnownServiceName,
  ServiceName,
  KnownProvisioningState,
  ProvisioningState,
  ServiceConfigurationResourcePatch,
  ServiceConfigurationPropertiesPatch,
  EndpointResource,
  EndpointProperties,
  KnownType,
  Type,
  ListCredentialsRequest,
  EndpointAccessResource,
  RelayNamespaceAccessProperties,
  IngressGatewayResource,
  IngressProfileProperties,
  AADProfileProperties,
  ManagedProxyRequest,
  ManagedProxyResource,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  KnownVersions,
} from "./models/index.js";
export {
  HybridConnectivityManagementAPIClientOptionalParams,
  OperationsListOptionalParams,
  EndpointsGetOptionalParams,
  EndpointsCreateOrUpdateOptionalParams,
  EndpointsUpdateOptionalParams,
  EndpointsDeleteOptionalParams,
  EndpointsListOptionalParams,
  EndpointsListCredentialsOptionalParams,
  EndpointsListIngressGatewayCredentialsOptionalParams,
  EndpointsListManagedProxyDetailsOptionalParams,
  ServiceConfigurationsGetOptionalParams,
  ServiceConfigurationsCreateOrupdateOptionalParams,
  ServiceConfigurationsUpdateOptionalParams,
  ServiceConfigurationsDeleteOptionalParams,
  ServiceConfigurationsListByEndpointResourceOptionalParams,
  GenerateAwsTemplatePostOptionalParams,
  PublicCloudConnectorsGetOptionalParams,
  PublicCloudConnectorsCreateOrUpdateOptionalParams,
  PublicCloudConnectorsUpdateOptionalParams,
  PublicCloudConnectorsDeleteOptionalParams,
  PublicCloudConnectorsListByResourceGroupOptionalParams,
  PublicCloudConnectorsListBySubscriptionOptionalParams,
  PublicCloudConnectorsTestPermissionsOptionalParams,
  SolutionConfigurationsGetOptionalParams,
  SolutionConfigurationsCreateOrUpdateOptionalParams,
  SolutionConfigurationsUpdateOptionalParams,
  SolutionConfigurationsDeleteOptionalParams,
  SolutionConfigurationsListOptionalParams,
  SolutionConfigurationsSyncNowOptionalParams,
  InventoryGetOptionalParams,
  InventoryListBySolutionConfigurationOptionalParams,
  SolutionTypesGetOptionalParams,
  SolutionTypesListByResourceGroupOptionalParams,
  SolutionTypesListBySubscriptionOptionalParams,
} from "./api/index.js";
export {
  EndpointsOperations,
  GenerateAwsTemplateOperations,
  InventoryOperations,
  OperationsOperations,
  PublicCloudConnectorsOperations,
  ServiceConfigurationsOperations,
  SolutionConfigurationsOperations,
  SolutionTypesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
