// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { NotificationHubsClient } from "./notificationHubsClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Operation,
  OperationDisplay,
  OperationProperties,
  ServiceSpecification,
  LogSpecification,
  MetricSpecification,
  Availability,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  NotificationHubResource,
  NotificationHubProperties,
  SharedAccessAuthorizationRuleProperties,
  KnownAccessRights,
  AccessRights,
  ApnsCredential,
  ApnsCredentialProperties,
  WnsCredential,
  WnsCredentialProperties,
  GcmCredential,
  GcmCredentialProperties,
  MpnsCredential,
  MpnsCredentialProperties,
  AdmCredential,
  AdmCredentialProperties,
  BaiduCredential,
  BaiduCredentialProperties,
  BrowserCredential,
  BrowserCredentialProperties,
  XiaomiCredential,
  XiaomiCredentialProperties,
  FcmV1Credential,
  FcmV1CredentialProperties,
  Sku,
  KnownSkuName,
  SkuName,
  TrackedResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  NotificationHubPatchParameters,
  DebugSendResponse,
  DebugSendResult,
  RegistrationResult,
  ProxyResource,
  PnsCredentialsResource,
  PnsCredentials,
  NamespaceResource,
  NamespaceProperties,
  KnownOperationProvisioningState,
  OperationProvisioningState,
  KnownNamespaceStatus,
  NamespaceStatus,
  KnownNamespaceType,
  NamespaceType,
  KnownReplicationRegion,
  ReplicationRegion,
  KnownZoneRedundancyPreference,
  ZoneRedundancyPreference,
  NetworkAcls,
  IpRule,
  PublicInternetAuthorizationRule,
  PrivateEndpointConnectionResource,
  PrivateEndpointConnectionProperties,
  KnownPrivateEndpointConnectionProvisioningState,
  PrivateEndpointConnectionProvisioningState,
  RemotePrivateEndpointConnection,
  RemotePrivateLinkServiceConnectionState,
  KnownPrivateLinkConnectionStatus,
  PrivateLinkConnectionStatus,
  KnownPublicNetworkAccess,
  PublicNetworkAccess,
  NamespacePatchParameters,
  CheckAvailabilityParameters,
  CheckAvailabilityResult,
  SharedAccessAuthorizationRuleResource,
  ResourceListKeys,
  PolicyKeyResource,
  KnownPolicyKeyType,
  PolicyKeyType,
  PrivateLinkResource,
  PrivateLinkResourceProperties,
  KnownVersions,
} from "./models/index.js";
export { NotificationHubsClientOptionalParams } from "./api/index.js";
export {
  NamespaceResourcesGetPnsCredentialsOptionalParams,
  NamespaceResourcesCheckNotificationHubAvailabilityOptionalParams,
  NamespaceResourcesListAllOptionalParams,
  NamespaceResourcesListOptionalParams,
  NamespaceResourcesDeleteOptionalParams,
  NamespaceResourcesUpdateOptionalParams,
  NamespaceResourcesCreateOrUpdateOptionalParams,
  NamespaceResourcesGetOptionalParams,
} from "./api/namespaceResources/index.js";
export {
  NamespacesRegenerateKeysOptionalParams,
  NamespacesListKeysOptionalParams,
  NamespacesListAuthorizationRulesOptionalParams,
  NamespacesDeleteAuthorizationRuleOptionalParams,
  NamespacesCreateOrUpdateAuthorizationRuleOptionalParams,
  NamespacesGetAuthorizationRuleOptionalParams,
} from "./api/namespaces/index.js";
export { NamespacesOperationGroupCheckAvailabilityOptionalParams } from "./api/namespacesOperationGroup/index.js";
export {
  NotificationHubResourcesGetPnsCredentialsOptionalParams,
  NotificationHubResourcesDebugSendOptionalParams,
  NotificationHubResourcesListOptionalParams,
  NotificationHubResourcesDeleteOptionalParams,
  NotificationHubResourcesUpdateOptionalParams,
  NotificationHubResourcesCreateOrUpdateOptionalParams,
  NotificationHubResourcesGetOptionalParams,
} from "./api/notificationHubResources/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  PrivateEndpointConnectionResourcesListOptionalParams,
  PrivateEndpointConnectionResourcesDeleteOptionalParams,
  PrivateEndpointConnectionResourcesUpdateOptionalParams,
  PrivateEndpointConnectionResourcesGetOptionalParams,
} from "./api/privateEndpointConnectionResources/index.js";
export {
  PrivateLinkResourcesListGroupIdsOptionalParams,
  PrivateLinkResourcesGetGroupIdOptionalParams,
} from "./api/privateLinkResources/index.js";
export {
  SharedAccessAuthorizationRuleResourcesRegenerateKeysOptionalParams,
  SharedAccessAuthorizationRuleResourcesListKeysOptionalParams,
  SharedAccessAuthorizationRuleResourcesListAuthorizationRulesOptionalParams,
  SharedAccessAuthorizationRuleResourcesDeleteAuthorizationRuleOptionalParams,
  SharedAccessAuthorizationRuleResourcesCreateOrUpdateAuthorizationRuleOptionalParams,
  SharedAccessAuthorizationRuleResourcesGetAuthorizationRuleOptionalParams,
} from "./api/sharedAccessAuthorizationRuleResources/index.js";
export {
  NamespaceResourcesOperations,
  NamespacesOperations,
  NamespacesOperationGroupOperations,
  NotificationHubResourcesOperations,
  OperationsOperations,
  PrivateEndpointConnectionResourcesOperations,
  PrivateLinkResourcesOperations,
  SharedAccessAuthorizationRuleResourcesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
