# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/azure-eval-svc-typespec_1/
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/azure-eval-svc-typespec_1/
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: azure-eval-svc-typespec_1
    Artifacts:
      - name: azure-rest- microsoft-machinelearningservices-rest
        safeName: azurerest microsoftmachinelearningservicesrest
