# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/deviceregistry/
    exclude:
      - sdk/deviceregistry/arm-deviceregistry
      - sdk/deviceregistry/ci.mgmt.yml
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/deviceregistry/
    exclude:
      - sdk/deviceregistry/arm-deviceregistry
      - sdk/deviceregistry/ci.mgmt.yml
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: deviceregistry
    Artifacts:
      - name: YOUR_PACKAGE_NAME
        safeName: YOUR_PACKAGE_NAME
