# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/scvmm/arm-scvmm
      - sdk/scvmm/ci.mgmt.yml
      - sdk/scvmm/arm-scvmmtest
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/scvmm/arm-scvmm
      - sdk/scvmm/ci.mgmt.yml
      - sdk/scvmm/arm-scvmmtest
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: scvmm
    Artifacts:
      - name: azure-arm-scvmm
        safeName: azurearmscvmm
      - name: azure-arm-scvmmtest
        safeName: azurearmscvmmtest
