// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  LoadTestResource,
  LoadTestProperties,
  KnownResourceState,
  ResourceState,
  EncryptionProperties,
  EncryptionPropertiesIdentity,
  KnownType,
  Type,
  ManagedServiceIdentity,
  KnownManagedServiceIdentityType,
  ManagedServiceIdentityType,
  UserAssignedIdentity,
  TrackedResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  LoadTestResourceUpdate,
  LoadTestResourceUpdateProperties,
  OutboundEnvironmentEndpoint,
  EndpointDependency,
  EndpointDetail,
  QuotaResource,
  QuotaResourceProperties,
  ProxyResource,
  QuotaBucketRequest,
  QuotaBucketRequestProperties,
  QuotaBucketRequestPropertiesDimensions,
  CheckQuotaAvailabilityResponse,
  CheckQuotaAvailabilityResponseProperties,
  KnownAPIVersions,
} from "./models.js";
