// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  TrackedResource,
  LoadTestResource,
  LoadTestProperties,
  KnownResourceProvisioningState,
  ResourceProvisioningState,
  EncryptionProperties,
  EncryptionPropertiesIdentity,
  KnownType,
  Type,
  ManagedServiceIdentity,
  KnownManagedServiceIdentityType,
  ManagedServiceIdentityType,
  UserAssignedIdentity,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  LoadTestResourceUpdate,
  LoadTestResourceUpdateProperties,
  OutboundEnvironmentEndpoint,
  EndpointDependency,
  EndpointDetail,
  ProxyResource,
  QuotaResource,
  QuotaResourceProperties,
  QuotaBucketRequest,
  QuotaBucketRequestProperties,
  QuotaBucketRequestPropertiesDimensions,
  CheckQuotaAvailabilityResponse,
  CheckQuotaAvailabilityResponseProperties,
  APIVersions,
  ResourceState,
} from "./models.js";
export {
  ListBySubscriptionOptionalParams,
  ListByResourceGroupOptionalParams,
  GetLoadtestOptionalParams,
  CreateOrUpdateLoadtestOptionalParams,
  UpdateLoadtestOptionalParams,
  DeleteLoadtestOptionalParams,
  OutboundNetworkDependenciesEndpointsOptionalParams,
  GetQuotaOptionalParams,
  ListQuotaOptionalParams,
  CheckAvailabilityQuotaOptionalParams,
} from "./options.js";
