// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ProxyResource,
  ServerInstance,
  ServerInstanceProperties,
  KnownSapInstanceType,
  SapInstanceType,
  KnownOperatingSystem,
  OperatingSystem,
  ConfigurationData,
  KnownDatabaseType,
  DatabaseType,
  PerformanceData,
  ExcelPerformanceData,
  NativePerformanceData,
  KnownDataSource,
  DataSource,
  KnownProvisioningState,
  ProvisioningState,
  SAPMigrateError,
  ErrorDefinition,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  UpdateServerInstanceRequest,
  TrackedResource,
  SAPInstance,
  SAPInstanceProperties,
  KnownSapInstanceEnvironment,
  SapInstanceEnvironment,
  SAPInstanceTagsUpdate,
  SAPDiscoverySite,
  SAPDiscoverySiteProperties,
  ExtendedLocation,
  SAPDiscoverySiteTagsUpdate,
  OperationStatusResult,
  Versions,
  PerformanceDataUnion,
} from "./models.js";
export {
  SAPDiscoverySitesGetOptionalParams,
  SAPDiscoverySitesCreateOptionalParams,
  SAPDiscoverySitesUpdateOptionalParams,
  SAPDiscoverySitesDeleteOptionalParams,
  SAPDiscoverySitesListByResourceGroupOptionalParams,
  SAPDiscoverySitesListBySubscriptionOptionalParams,
  SAPDiscoverySitesImportEntitiesOptionalParams,
  SAPInstancesGetOptionalParams,
  SAPInstancesCreateOptionalParams,
  SAPInstancesUpdateOptionalParams,
  SAPInstancesDeleteOptionalParams,
  SAPInstancesListBySapDiscoverySiteOptionalParams,
  ServerInstancesGetOptionalParams,
  ServerInstancesCreateOptionalParams,
  ServerInstancesUpdateOptionalParams,
  ServerInstancesDeleteOptionalParams,
  ServerInstancesListBySapInstanceOptionalParams,
} from "./options.js";
