// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { MonitorClient } from "./monitorClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  AzureMonitorWorkspace,
  AzureMonitorWorkspaceProperties,
  Metrics,
  KnownProvisioningState,
  ProvisioningState,
  IngestionSettings,
  PrivateEndpointConnection,
  PrivateEndpointConnectionProperties,
  PrivateEndpoint,
  PrivateLinkServiceConnectionState,
  KnownPrivateEndpointServiceConnectionStatus,
  PrivateEndpointServiceConnectionStatus,
  KnownPrivateEndpointConnectionProvisioningState,
  PrivateEndpointConnectionProvisioningState,
  KnownPublicNetworkAccess,
  PublicNetworkAccess,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  TrackedResource,
  AzureMonitorWorkspaceUpdate,
  AzureMonitorWorkspaceUpdateProperties,
  PipelineGroup,
  PipelineGroupProperties,
  Receiver,
  KnownReceiverType,
  ReceiverType,
  SyslogReceiver,
  KnownSyslogProtocol,
  SyslogProtocol,
  OtlpReceiver,
  UdpReceiver,
  KnownStreamEncodingType,
  StreamEncodingType,
  Processor,
  KnownProcessorType,
  ProcessorType,
  BatchProcessor,
  Exporter,
  KnownExporterType,
  ExporterType,
  AzureMonitorWorkspaceLogsExporter,
  AzureMonitorWorkspaceLogsApiConfig,
  SchemaMap,
  RecordMap,
  ResourceMap,
  ScopeMap,
  ConcurrencyConfiguration,
  CacheConfiguration,
  TcpExporter,
  Service,
  Pipeline,
  KnownPipelineType,
  PipelineType,
  PersistenceConfigurations,
  NetworkingConfiguration,
  KnownExternalNetworkingMode,
  ExternalNetworkingMode,
  NetworkingRoute,
  ExtendedLocation,
  KnownExtendedLocationType,
  ExtendedLocationType,
  PipelineGroupUpdate,
  PipelineGroupUpdateProperties,
  KnownVersions,
} from "./models/index.js";
export { MonitorClientOptionalParams } from "./api/index.js";
export {
  AzureMonitorWorkspacesListBySubscriptionOptionalParams,
  AzureMonitorWorkspacesListByResourceGroupOptionalParams,
  AzureMonitorWorkspacesDeleteOptionalParams,
  AzureMonitorWorkspacesUpdateOptionalParams,
  AzureMonitorWorkspacesCreateOrUpdateOptionalParams,
  AzureMonitorWorkspacesGetOptionalParams,
} from "./api/azureMonitorWorkspaces/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  PipelineGroupsListBySubscriptionOptionalParams,
  PipelineGroupsListByResourceGroupOptionalParams,
  PipelineGroupsUpdateOptionalParams,
  PipelineGroupsDeleteOptionalParams,
  PipelineGroupsCreateOrUpdateOptionalParams,
  PipelineGroupsGetOptionalParams,
} from "./api/pipelineGroups/index.js";
export {
  AzureMonitorWorkspacesOperations,
  OperationsOperations,
  PipelineGroupsOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
