/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import { SimplePollerLike, OperationState } from "@azure/core-lro";
import {
  RedisPatchSchedule,
  PatchSchedulesListByRedisResourceOptionalParams,
  DefaultName,
  PatchSchedulesCreateOrUpdateOptionalParams,
  PatchSchedulesCreateOrUpdateResponse,
  PatchSchedulesDeleteOptionalParams,
  PatchSchedulesGetOptionalParams,
  PatchSchedulesGetResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a PatchSchedules. */
export interface PatchSchedules {
  /**
   * Gets all patch schedules in the specified redis cache (there is only one).
   * @param resourceGroupName The name of the resource group.
   * @param cacheName The name of the Redis cache.
   * @param options The options parameters.
   */
  listByRedisResource(
    resourceGroupName: string,
    cacheName: string,
    options?: PatchSchedulesListByRedisResourceOptionalParams
  ): PagedAsyncIterableIterator<RedisPatchSchedule>;
  /**
   * Create or replace the patching schedule for Redis cache.
   * @param resourceGroupName The name of the resource group.
   * @param name The name of the Redis cache.
   * @param defaultParam Default string modeled as parameter for auto generation to work correctly.
   * @param parameters Parameters to set the patching schedule for Redis cache.
   * @param options The options parameters.
   */
  beginCreateOrUpdate(
    resourceGroupName: string,
    name: string,
    defaultParam: DefaultName,
    parameters: RedisPatchSchedule,
    options?: PatchSchedulesCreateOrUpdateOptionalParams
  ): Promise<
    SimplePollerLike<
      OperationState<PatchSchedulesCreateOrUpdateResponse>,
      PatchSchedulesCreateOrUpdateResponse
    >
  >;
  /**
   * Create or replace the patching schedule for Redis cache.
   * @param resourceGroupName The name of the resource group.
   * @param name The name of the Redis cache.
   * @param defaultParam Default string modeled as parameter for auto generation to work correctly.
   * @param parameters Parameters to set the patching schedule for Redis cache.
   * @param options The options parameters.
   */
  beginCreateOrUpdateAndWait(
    resourceGroupName: string,
    name: string,
    defaultParam: DefaultName,
    parameters: RedisPatchSchedule,
    options?: PatchSchedulesCreateOrUpdateOptionalParams
  ): Promise<PatchSchedulesCreateOrUpdateResponse>;
  /**
   * Deletes the patching schedule of a redis cache.
   * @param resourceGroupName The name of the resource group.
   * @param name The name of the redis cache.
   * @param defaultParam Default string modeled as parameter for auto generation to work correctly.
   * @param options The options parameters.
   */
  beginDelete(
    resourceGroupName: string,
    name: string,
    defaultParam: DefaultName,
    options?: PatchSchedulesDeleteOptionalParams
  ): Promise<SimplePollerLike<OperationState<void>, void>>;
  /**
   * Deletes the patching schedule of a redis cache.
   * @param resourceGroupName The name of the resource group.
   * @param name The name of the redis cache.
   * @param defaultParam Default string modeled as parameter for auto generation to work correctly.
   * @param options The options parameters.
   */
  beginDeleteAndWait(
    resourceGroupName: string,
    name: string,
    defaultParam: DefaultName,
    options?: PatchSchedulesDeleteOptionalParams
  ): Promise<void>;
  /**
   * Gets the patching schedule of a redis cache.
   * @param resourceGroupName The name of the resource group.
   * @param name The name of the redis cache.
   * @param defaultParam Default string modeled as parameter for auto generation to work correctly.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    name: string,
    defaultParam: DefaultName,
    options?: PatchSchedulesGetOptionalParams
  ): Promise<PatchSchedulesGetResponse>;
}
