# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/toolchainorchestrator/arm-toolchainorchestrator
      - sdk/toolchainorchestrator/ci.mgmt.yml
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/toolchainorchestrator/arm-toolchainorchestrator
      - sdk/toolchainorchestrator/ci.mgmt.yml
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: sdk/toolchainorchestrator
    Artifacts:
      - name: azure-arm-toolchainorchestrator
        safeName: azurearmtoolchainorchestrator
