// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { EdgeOrderClient } from "./edgeOrderClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  AddressResource,
  AddressProperties,
  KnownAddressClassification,
  AddressClassification,
  ShippingAddress,
  KnownAddressType,
  AddressType,
  ContactDetails,
  KnownAddressValidationStatus,
  AddressValidationStatus,
  KnownProvisioningState,
  ProvisioningState,
  TrackedResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  AddressUpdateParameter,
  AddressUpdateProperties,
  OrderItemResource,
  OrderItemProperties,
  OrderItemDetails,
  ProductDetails,
  DisplayInfo,
  HierarchyInformation,
  KnownDoubleEncryptionStatus,
  DoubleEncryptionStatus,
  KnownIdentificationType,
  IdentificationType,
  DeviceDetails,
  KnownProvisioningSupport,
  ProvisioningSupport,
  ProvisioningDetails,
  KnownAutoProvisioningStatus,
  AutoProvisioningStatus,
  DevicePresenceVerificationDetails,
  KnownDevicePresenceVerificationStatus,
  DevicePresenceVerificationStatus,
  AdditionalConfiguration,
  ConfigurationDeviceDetails,
  TermCommitmentInformation,
  KnownTermCommitmentType,
  TermCommitmentType,
  KnownOrderItemType,
  OrderItemType,
  KnownOrderMode,
  OrderMode,
  SiteDetails,
  StageDetails,
  KnownStageStatus,
  StageStatus,
  KnownStageName,
  StageName,
  Preferences,
  NotificationPreference,
  KnownNotificationStageName,
  NotificationStageName,
  TransportPreferences,
  KnownTransportShipmentTypes,
  TransportShipmentTypes,
  EncryptionPreferences,
  ManagementResourcePreferences,
  TermCommitmentPreferences,
  ForwardShippingDetails,
  ReverseShippingDetails,
  KnownOrderItemCancellationEnum,
  OrderItemCancellationEnum,
  KnownActionStatusEnum,
  ActionStatusEnum,
  KnownOrderItemReturnEnum,
  OrderItemReturnEnum,
  ResourceProviderDetails,
  AddressDetails,
  ResourceIdentity,
  UserAssignedIdentity,
  OrderItemUpdateParameter,
  OrderItemUpdateProperties,
  OrderItemDetailsUpdateParameter,
  ProductDetailsUpdateParameter,
  CancellationReason,
  ReturnOrderItemDetails,
  OkResponse,
  OrderResource,
  OrderProperties,
  ProxyResource,
  ConfigurationsRequest,
  ConfigurationFilter,
  FilterableProperty,
  KnownSupportedFilterTypes,
  SupportedFilterTypes,
  ChildConfigurationFilter,
  KnownChildConfigurationType,
  ChildConfigurationType,
  CustomerSubscriptionDetails,
  CustomerSubscriptionRegisteredFeatures,
  Configuration,
  ConfigurationProperties,
  Specification,
  Dimensions,
  KnownLengthHeightUnit,
  LengthHeightUnit,
  KnownWeightMeasurementUnit,
  WeightMeasurementUnit,
  GroupedChildConfigurations,
  CategoryInformation,
  Link,
  KnownLinkType,
  LinkType,
  ChildConfiguration,
  ChildConfigurationProperties,
  Description,
  KnownDescriptionType,
  DescriptionType,
  ImageInformation,
  KnownImageType,
  ImageType,
  CostInformation,
  BillingMeterDetails,
  MeterDetails,
  MeterDetailsUnion,
  KnownBillingType,
  BillingType,
  KnownChargingType,
  ChargingType,
  Pav2MeterDetails,
  PurchaseMeterDetails,
  KnownMeteringType,
  MeteringType,
  TermTypeDetails,
  AvailabilityInformation,
  KnownAvailabilityStage,
  AvailabilityStage,
  KnownDisabledReason,
  DisabledReason,
  KnownFulfillmentType,
  FulfillmentType,
  CommonProperties,
  BasicInformation,
  ProductFamiliesRequest,
  ProductFamily,
  ProductFamilyProperties,
  ProductLine,
  ProductLineProperties,
  Product,
  ProductProperties,
  ProductFamiliesMetadataDetails,
  KnownVersions,
} from "./models/index.js";
export { EdgeOrderClientOptionalParams } from "./api/index.js";
export {
  AddressResourcesListBySubscriptionOptionalParams,
  AddressResourcesListByResourceGroupOptionalParams,
  AddressResourcesDeleteOptionalParams,
  AddressResourcesUpdateOptionalParams,
  AddressResourcesCreateOptionalParams,
  AddressResourcesGetOptionalParams,
} from "./api/addressResources/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  OrderItemResourcesReturnOrderItemOptionalParams,
  OrderItemResourcesCancelOptionalParams,
  OrderItemResourcesListBySubscriptionOptionalParams,
  OrderItemResourcesListByResourceGroupOptionalParams,
  OrderItemResourcesDeleteOptionalParams,
  OrderItemResourcesUpdateOptionalParams,
  OrderItemResourcesCreateOptionalParams,
  OrderItemResourcesGetOptionalParams,
} from "./api/orderItemResources/index.js";
export { OrderResourcesGetOptionalParams } from "./api/orderResources/index.js";
export {
  OrdersOperationGroupListByResourceGroupOptionalParams,
  OrdersOperationGroupListBySubscriptionOptionalParams,
} from "./api/ordersOperationGroup/index.js";
export {
  ProductsAndConfigurationsOperationGroupListProductFamiliesMetadataOptionalParams,
  ProductsAndConfigurationsOperationGroupListProductFamiliesOptionalParams,
  ProductsAndConfigurationsOperationGroupListConfigurationsOptionalParams,
} from "./api/productsAndConfigurationsOperationGroup/index.js";
export {
  AddressResourcesOperations,
  OperationsOperations,
  OrderItemResourcesOperations,
  OrderResourcesOperations,
  OrdersOperationGroupOperations,
  ProductsAndConfigurationsOperationGroupOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
