# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
            
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/fairfieldgardens/arm-fairfieldgardens
      - sdk/fairfieldgardens/ci.mgmt.yml

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/fairfieldgardens/arm-fairfieldgardens
      - sdk/fairfieldgardens/ci.mgmt.yml

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: fairfieldgardens
    Artifacts:
      - name: azure-arm-fairfieldgardens
        safeName: azurearmfairfieldgardens
        