/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  WorkflowExportRequest,
  LocationsValidateWorkflowExportOptionalParams,
  LocationsValidateWorkflowExportResponse,
  LocationsWorkflowExportOptionalParams,
  LocationsWorkflowExportResponse
} from "../models";

/** Interface representing a Locations. */
export interface Locations {
  /**
   * Validates the workflow export.
   * @param location The name of Azure region.
   * @param workflowExportRequest The workflow export request.
   * @param options The options parameters.
   */
  validateWorkflowExport(
    location: string,
    workflowExportRequest: WorkflowExportRequest,
    options?: LocationsValidateWorkflowExportOptionalParams
  ): Promise<LocationsValidateWorkflowExportResponse>;
  /**
   * Executes the workflow export.
   * @param location The name of Azure region.
   * @param workflowExportRequest The workflow export request.
   * @param options The options parameters.
   */
  workflowExport(
    location: string,
    workflowExportRequest: WorkflowExportRequest,
    options?: LocationsWorkflowExportOptionalParams
  ): Promise<LocationsWorkflowExportResponse>;
}
