// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export {
  WorkloadsClient,
  WorkloadsClientOptionalParams,
} from "./workloadsClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ProxyResource,
  ServerInstance,
  ServerInstanceProperties,
  KnownSapInstanceType,
  SapInstanceType,
  KnownOperatingSystem,
  OperatingSystem,
  ConfigurationData,
  KnownDatabaseType,
  DatabaseType,
  PerformanceData,
  ExcelPerformanceData,
  NativePerformanceData,
  KnownDataSource,
  DataSource,
  KnownProvisioningState,
  ProvisioningState,
  SAPMigrateError,
  ErrorDefinition,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  UpdateServerInstanceRequest,
  TrackedResource,
  SAPInstance,
  SAPInstanceProperties,
  KnownSapInstanceEnvironment,
  SapInstanceEnvironment,
  SAPInstanceTagsUpdate,
  SAPDiscoverySite,
  SAPDiscoverySiteProperties,
  ExtendedLocation,
  SAPDiscoverySiteTagsUpdate,
  OperationStatusResult,
  Versions,
  PerformanceDataUnion,
  SAPDiscoverySitesGetOptionalParams,
  SAPDiscoverySitesCreateOptionalParams,
  SAPDiscoverySitesUpdateOptionalParams,
  SAPDiscoverySitesDeleteOptionalParams,
  SAPDiscoverySitesListByResourceGroupOptionalParams,
  SAPDiscoverySitesListBySubscriptionOptionalParams,
  SAPDiscoverySitesImportEntitiesOptionalParams,
  SAPInstancesGetOptionalParams,
  SAPInstancesCreateOptionalParams,
  SAPInstancesUpdateOptionalParams,
  SAPInstancesDeleteOptionalParams,
  SAPInstancesListBySapDiscoverySiteOptionalParams,
  ServerInstancesGetOptionalParams,
  ServerInstancesCreateOptionalParams,
  ServerInstancesUpdateOptionalParams,
  ServerInstancesDeleteOptionalParams,
  ServerInstancesListBySapInstanceOptionalParams,
} from "./models/index.js";
export {
  SAPDiscoverySitesOperations,
  SAPInstancesOperations,
  ServerInstancesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
