// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { ElasticClient } from "./elasticClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  OperationResult,
  OperationDisplay,
  ResourceProviderDefaultErrorResponse,
  ErrorResponseBody,
  ElasticMonitorResource,
  MonitorProperties,
  KnownProvisioningState,
  ProvisioningState,
  KnownMonitoringStatus,
  MonitoringStatus,
  ElasticProperties,
  ElasticCloudUser,
  ElasticCloudDeployment,
  UserInfo,
  CompanyInfo,
  PlanDetails,
  KnownLiftrResourceCategories,
  LiftrResourceCategories,
  KnownHostingType,
  HostingType,
  ProjectDetails,
  KnownProjectType,
  ProjectType,
  KnownConfigurationType,
  ConfigurationType,
  ResourceSku,
  IdentityProperties,
  KnownManagedIdentityTypes,
  ManagedIdentityTypes,
  TrackedResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorDetail,
  ErrorAdditionalInfo,
  ElasticMonitorResourceUpdateParameters,
  ErrorResponse,
  MonitoredResource,
  KnownSendingLogs,
  SendingLogs,
  DeploymentInfoResponse,
  KnownElasticDeploymentStatus,
  ElasticDeploymentStatus,
  MarketplaceSaaSInfo,
  MarketplaceSaaSInfoMarketplaceSubscription,
  ExternalUserInfo,
  ExternalUserCreationResponse,
  BillingInfoResponse,
  PartnerBillingEntity,
  ConnectedPartnerResourcesListFormat,
  ConnectedPartnerResourceProperties,
  VMResources,
  VMIngestionDetailsResponse,
  VMCollectionUpdate,
  KnownOperationName,
  OperationName,
  UpgradableVersionsList,
  ElasticMonitorUpgrade,
  ElasticTrafficFilterResponse,
  ElasticTrafficFilter,
  KnownType,
  Type,
  ElasticTrafficFilterRule,
  OkResponse,
  ResubscribeProperties,
  ArmResponseElasticMonitorResource,
  MonitoredSubscriptionProperties,
  SubscriptionList,
  KnownOperation,
  Operation,
  MonitoredSubscription,
  KnownStatus,
  Status,
  MonitoringTagRulesProperties,
  LogRules,
  FilteringTag,
  KnownTagAction,
  TagAction,
  ProxyResource,
  OpenAIIntegrationRPModel,
  OpenAIIntegrationProperties,
  OpenAIIntegrationStatusResponse,
  OpenAIIntegrationStatusResponseProperties,
  MonitoringTagRules,
  ElasticVersionListFormat,
  ElasticVersionListProperties,
  UserEmailId,
  UserApiKeyResponse,
  UserApiKeyResponseProperties,
  ElasticOrganizationToAzureSubscriptionMappingResponse,
  ElasticOrganizationToAzureSubscriptionMappingResponseProperties,
  KnownVersions,
} from "./models/index.js";
export { ElasticClientOptionalParams } from "./api/index.js";
export {
  ElasticMonitorResourcesResubscribeOptionalParams,
  ElasticMonitorResourcesTrafficFiltersDeleteOptionalParams,
  ElasticMonitorResourcesDetachTrafficFilterUpdateOptionalParams,
  ElasticMonitorResourcesDetachAndDeleteTrafficFilterDeleteOptionalParams,
  ElasticMonitorResourcesAssociateOptionalParams,
  ElasticMonitorResourcesCreateAndAssociatePLFilterCreateOptionalParams,
  ElasticMonitorResourcesCreateAndAssociateIPFilterCreateOptionalParams,
  ElasticMonitorResourcesListAssociatedTrafficFiltersListOptionalParams,
  ElasticMonitorResourcesAllTrafficFiltersListOptionalParams,
  ElasticMonitorResourcesUpgradeOptionalParams,
  ElasticMonitorResourcesUpgradableVersionsDetailsOptionalParams,
  ElasticMonitorResourcesVMCollectionUpdateOptionalParams,
  ElasticMonitorResourcesDetailsOptionalParams,
  ElasticMonitorResourcesVMHostListOptionalParams,
  ElasticMonitorResourcesConnectedPartnerResourcesListOptionalParams,
  ElasticMonitorResourcesBillingInfoGetOptionalParams,
  ElasticMonitorResourcesCreateOrUpdateOptionalParams,
  ElasticMonitorResourcesDeploymentInfoListOptionalParams,
  ElasticMonitorResourcesMonitoredResourcesListOptionalParams,
  ElasticMonitorResourcesListOptionalParams,
  ElasticMonitorResourcesListByResourceGroupOptionalParams,
  ElasticMonitorResourcesDeleteOptionalParams,
  ElasticMonitorResourcesUpdateOptionalParams,
  ElasticMonitorResourcesCreateOptionalParams,
  ElasticMonitorResourcesGetOptionalParams,
} from "./api/elasticMonitorResources/index.js";
export { ElasticVersionsOperationGroupListOptionalParams } from "./api/elasticVersionsOperationGroup/index.js";
export {
  MonitoredSubscriptionsListOptionalParams,
  MonitoredSubscriptionsDeleteOptionalParams,
  MonitoredSubscriptionsUpdateOptionalParams,
  MonitoredSubscriptionsCreateorUpdateOptionalParams,
  MonitoredSubscriptionsGetOptionalParams,
} from "./api/monitoredSubscriptions/index.js";
export {
  OpenAIIntegrationRPModelsGetStatusOptionalParams,
  OpenAIIntegrationRPModelsListOptionalParams,
  OpenAIIntegrationRPModelsDeleteOptionalParams,
  OpenAIIntegrationRPModelsCreateOrUpdateOptionalParams,
  OpenAIIntegrationRPModelsGetOptionalParams,
} from "./api/openAIIntegrationRPModels/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  OrganizationsOperationGroupGetElasticToAzureSubscriptionMappingOptionalParams,
  OrganizationsOperationGroupGetApiKeyOptionalParams,
} from "./api/organizationsOperationGroup/index.js";
export {
  TagRulesListOptionalParams,
  TagRulesDeleteOptionalParams,
  TagRulesCreateOrUpdateOptionalParams,
  TagRulesGetOptionalParams,
} from "./api/tagRules/index.js";
export {
  ElasticMonitorResourcesOperations,
  ElasticVersionsOperationGroupOperations,
  MonitoredSubscriptionsOperations,
  OpenAIIntegrationRPModelsOperations,
  OperationsOperations,
  OrganizationsOperationGroupOperations,
  TagRulesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
