/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator, PageSettings } from "@azure/core-paging";
import { setContinuationToken } from "../pagingHelper";
import { FirewallRules } from "../operationsInterfaces";
import * as coreClient from "@azure/core-client";
import * as Mappers from "../models/mappers";
import * as Parameters from "../models/parameters";
import { MongoClusterManagementClient } from "../mongoClusterManagementClient";
import {
  SimplePollerLike,
  OperationState,
  createHttpPoller,
} from "@azure/core-lro";
import { createLroSpec } from "../lroImpl";
import {
  FirewallRule,
  FirewallRulesListByMongoClusterTestNextOptionalParams,
  FirewallRulesListByMongoClusterTestOptionalParams,
  FirewallRulesListByMongoClusterTestResponse,
  FirewallRulesGetOptionalParams,
  FirewallRulesGetResponse,
  FirewallRulesCreateOrUpdateOptionalParams,
  FirewallRulesCreateOrUpdateResponse,
  FirewallRulesDeleteOptionalParams,
  FirewallRulesDeleteResponse,
  FirewallRulesListByMongoClusterTestNextResponse,
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Class containing FirewallRules operations. */
export class FirewallRulesImpl implements FirewallRules {
  private readonly client: MongoClusterManagementClient;

  /**
   * Initialize a new instance of the class FirewallRules class.
   * @param client Reference to the service client
   */
  constructor(client: MongoClusterManagementClient) {
    this.client = client;
  }

  /**
   * List all the firewall rules in a given mongo cluster.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param options The options parameters.
   */
  public listByMongoClusterTest(
    resourceGroupName: string,
    mongoClusterName: string,
    options?: FirewallRulesListByMongoClusterTestOptionalParams,
  ): PagedAsyncIterableIterator<FirewallRule> {
    const iter = this.listByMongoClusterTestPagingAll(
      resourceGroupName,
      mongoClusterName,
      options,
    );
    return {
      next() {
        return iter.next();
      },
      [Symbol.asyncIterator]() {
        return this;
      },
      byPage: (settings?: PageSettings) => {
        if (settings?.maxPageSize) {
          throw new Error("maxPageSize is not supported by this operation.");
        }
        return this.listByMongoClusterTestPagingPage(
          resourceGroupName,
          mongoClusterName,
          options,
          settings,
        );
      },
    };
  }

  private async *listByMongoClusterTestPagingPage(
    resourceGroupName: string,
    mongoClusterName: string,
    options?: FirewallRulesListByMongoClusterTestOptionalParams,
    settings?: PageSettings,
  ): AsyncIterableIterator<FirewallRule[]> {
    let result: FirewallRulesListByMongoClusterTestResponse;
    let continuationToken = settings?.continuationToken;
    if (!continuationToken) {
      result = await this._listByMongoClusterTest(
        resourceGroupName,
        mongoClusterName,
        options,
      );
      let page = result.value || [];
      continuationToken = result.nextLink;
      setContinuationToken(page, continuationToken);
      yield page;
    }
    while (continuationToken) {
      result = await this._listByMongoClusterTestNext(
        resourceGroupName,
        mongoClusterName,
        continuationToken,
        options,
      );
      continuationToken = result.nextLink;
      let page = result.value || [];
      setContinuationToken(page, continuationToken);
      yield page;
    }
  }

  private async *listByMongoClusterTestPagingAll(
    resourceGroupName: string,
    mongoClusterName: string,
    options?: FirewallRulesListByMongoClusterTestOptionalParams,
  ): AsyncIterableIterator<FirewallRule> {
    for await (const page of this.listByMongoClusterTestPagingPage(
      resourceGroupName,
      mongoClusterName,
      options,
    )) {
      yield* page;
    }
  }

  /**
   * List all the firewall rules in a given mongo cluster.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param options The options parameters.
   */
  private _listByMongoClusterTest(
    resourceGroupName: string,
    mongoClusterName: string,
    options?: FirewallRulesListByMongoClusterTestOptionalParams,
  ): Promise<FirewallRulesListByMongoClusterTestResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, mongoClusterName, options },
      listByMongoClusterTestOperationSpec,
    );
  }

  /**
   * Gets information about a mongo cluster firewall rule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param firewallRuleName The name of the mongo cluster firewall rule.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    mongoClusterName: string,
    firewallRuleName: string,
    options?: FirewallRulesGetOptionalParams,
  ): Promise<FirewallRulesGetResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, mongoClusterName, firewallRuleName, options },
      getOperationSpec,
    );
  }

  /**
   * Creates a new firewall rule or updates an existing firewall rule on a mongo cluster.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param firewallRuleName The name of the mongo cluster firewall rule.
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  async beginCreateOrUpdate(
    resourceGroupName: string,
    mongoClusterName: string,
    firewallRuleName: string,
    resource: FirewallRule,
    options?: FirewallRulesCreateOrUpdateOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<FirewallRulesCreateOrUpdateResponse>,
      FirewallRulesCreateOrUpdateResponse
    >
  > {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec,
    ): Promise<FirewallRulesCreateOrUpdateResponse> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperationFn = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec,
    ) => {
      let currentRawResponse: coreClient.FullOperationResponse | undefined =
        undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown,
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback,
        },
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON(),
        },
      };
    };

    const lro = createLroSpec({
      sendOperationFn,
      args: {
        resourceGroupName,
        mongoClusterName,
        firewallRuleName,
        resource,
        options,
      },
      spec: createOrUpdateOperationSpec,
    });
    const poller = await createHttpPoller<
      FirewallRulesCreateOrUpdateResponse,
      OperationState<FirewallRulesCreateOrUpdateResponse>
    >(lro, {
      restoreFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs,
      resourceLocationConfig: "azure-async-operation",
    });
    await poller.poll();
    return poller;
  }

  /**
   * Creates a new firewall rule or updates an existing firewall rule on a mongo cluster.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param firewallRuleName The name of the mongo cluster firewall rule.
   * @param resource Resource create parameters.
   * @param options The options parameters.
   */
  async beginCreateOrUpdateAndWait(
    resourceGroupName: string,
    mongoClusterName: string,
    firewallRuleName: string,
    resource: FirewallRule,
    options?: FirewallRulesCreateOrUpdateOptionalParams,
  ): Promise<FirewallRulesCreateOrUpdateResponse> {
    const poller = await this.beginCreateOrUpdate(
      resourceGroupName,
      mongoClusterName,
      firewallRuleName,
      resource,
      options,
    );
    return poller.pollUntilDone();
  }

  /**
   * Deletes a mongo cluster firewall rule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param firewallRuleName The name of the mongo cluster firewall rule.
   * @param options The options parameters.
   */
  async beginDelete(
    resourceGroupName: string,
    mongoClusterName: string,
    firewallRuleName: string,
    options?: FirewallRulesDeleteOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<FirewallRulesDeleteResponse>,
      FirewallRulesDeleteResponse
    >
  > {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec,
    ): Promise<FirewallRulesDeleteResponse> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperationFn = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec,
    ) => {
      let currentRawResponse: coreClient.FullOperationResponse | undefined =
        undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown,
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback,
        },
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON(),
        },
      };
    };

    const lro = createLroSpec({
      sendOperationFn,
      args: { resourceGroupName, mongoClusterName, firewallRuleName, options },
      spec: deleteOperationSpec,
    });
    const poller = await createHttpPoller<
      FirewallRulesDeleteResponse,
      OperationState<FirewallRulesDeleteResponse>
    >(lro, {
      restoreFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs,
      resourceLocationConfig: "location",
    });
    await poller.poll();
    return poller;
  }

  /**
   * Deletes a mongo cluster firewall rule.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param firewallRuleName The name of the mongo cluster firewall rule.
   * @param options The options parameters.
   */
  async beginDeleteAndWait(
    resourceGroupName: string,
    mongoClusterName: string,
    firewallRuleName: string,
    options?: FirewallRulesDeleteOptionalParams,
  ): Promise<FirewallRulesDeleteResponse> {
    const poller = await this.beginDelete(
      resourceGroupName,
      mongoClusterName,
      firewallRuleName,
      options,
    );
    return poller.pollUntilDone();
  }

  /**
   * ListByMongoClusterTestNext
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param mongoClusterName The name of the mongo cluster.
   * @param nextLink The nextLink from the previous successful call to the ListByMongoClusterTest method.
   * @param options The options parameters.
   */
  private _listByMongoClusterTestNext(
    resourceGroupName: string,
    mongoClusterName: string,
    nextLink: string,
    options?: FirewallRulesListByMongoClusterTestNextOptionalParams,
  ): Promise<FirewallRulesListByMongoClusterTestNextResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, mongoClusterName, nextLink, options },
      listByMongoClusterTestNextOperationSpec,
    );
  }
}
// Operation Specifications
const serializer = coreClient.createSerializer(Mappers, /* isXml */ false);

const listByMongoClusterTestOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/mongoClusters/{mongoClusterName}/firewallRules",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.FirewallRuleListResult,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.mongoClusterName,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
const getOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/mongoClusters/{mongoClusterName}/firewallRules/{firewallRuleName}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.FirewallRule,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.mongoClusterName,
    Parameters.firewallRuleName,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
const createOrUpdateOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/mongoClusters/{mongoClusterName}/firewallRules/{firewallRuleName}",
  httpMethod: "PUT",
  responses: {
    200: {
      bodyMapper: Mappers.FirewallRule,
    },
    201: {
      bodyMapper: Mappers.FirewallRule,
    },
    202: {
      bodyMapper: Mappers.FirewallRule,
    },
    204: {
      bodyMapper: Mappers.FirewallRule,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  requestBody: Parameters.resource1,
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.mongoClusterName,
    Parameters.firewallRuleName,
  ],
  headerParameters: [Parameters.accept, Parameters.contentType],
  mediaType: "json",
  serializer,
};
const deleteOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/mongoClusters/{mongoClusterName}/firewallRules/{firewallRuleName}",
  httpMethod: "DELETE",
  responses: {
    200: {
      headersMapper: Mappers.FirewallRulesDeleteHeaders,
    },
    201: {
      headersMapper: Mappers.FirewallRulesDeleteHeaders,
    },
    202: {
      headersMapper: Mappers.FirewallRulesDeleteHeaders,
    },
    204: {
      headersMapper: Mappers.FirewallRulesDeleteHeaders,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.mongoClusterName,
    Parameters.firewallRuleName,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
const listByMongoClusterTestNextOperationSpec: coreClient.OperationSpec = {
  path: "{nextLink}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.FirewallRuleListResult,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  urlParameters: [
    Parameters.$host,
    Parameters.nextLink,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.mongoClusterName,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
