/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  MarketplaceImageSku,
  MarketplaceImageSkuListSKUsWithinOfferOptionalParams
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a MarketplaceImageSkuOperations. */
export interface MarketplaceImageSkuOperations {
  /**
   * Returns List of SKUs Within Offer
   * @param deviceName
   * @param publisherName
   * @param offerName
   * @param resourceGroupName The resource group name.
   * @param options The options parameters.
   */
  listSKUsWithinOffer(
    deviceName: string,
    publisherName: string,
    offerName: string,
    resourceGroupName: string,
    options?: MarketplaceImageSkuListSKUsWithinOfferOptionalParams
  ): PagedAsyncIterableIterator<MarketplaceImageSku>;
}
