// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { BotServiceClient } from "./botServiceClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  OperationEntity,
  OperationDisplayInfo,
  ErrorModel,
  ErrorBody,
  Bot,
  BotProperties,
  KnownMsaAppType,
  MsaAppType,
  KnownPublicNetworkAccess,
  PublicNetworkAccess,
  PrivateEndpointConnection,
  PrivateEndpointConnectionProperties,
  PrivateEndpoint,
  PrivateLinkServiceConnectionState,
  KnownPrivateEndpointServiceConnectionStatus,
  PrivateEndpointServiceConnectionStatus,
  KnownPrivateEndpointConnectionProvisioningState,
  PrivateEndpointConnectionProvisioningState,
  NetworkSecurityPerimeterConfiguration,
  NetworkSecurityPerimeterConfigurationProperties,
  KnownProvisioningState,
  ProvisioningState,
  ProvisioningIssue,
  ProvisioningIssueProperties,
  KnownSeverity,
  Severity,
  NspAccessRule,
  NspAccessRuleProperties,
  KnownNspAccessRuleDirection,
  NspAccessRuleDirection,
  NspAccessRulePropertiesSubscriptionsItem,
  NetworkSecurityPerimeter,
  ResourceAssociation,
  KnownAccessMode,
  AccessMode,
  Profile,
  Sku,
  KnownSkuName,
  SkuName,
  KnownSkuTier,
  SkuTier,
  KnownKind,
  Kind,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  TrackedResource,
  CreateEmailSignInUrlResponse,
  CreateEmailSignInUrlResponseProperties,
  PrivateLinkResourceListResult,
  PrivateLinkResource,
  PrivateLinkResourceProperties,
  PrivateLinkResourceBase,
  BotChannel,
  Channel,
  ChannelUnion,
  AlexaChannel,
  AlexaChannelProperties,
  FacebookChannel,
  FacebookChannelProperties,
  FacebookPage,
  EmailChannel,
  EmailChannelProperties,
  EmailChannelAuthMethod,
  OutlookChannel,
  MsTeamsChannel,
  MsTeamsChannelProperties,
  SkypeChannel,
  SkypeChannelProperties,
  KikChannel,
  KikChannelProperties,
  WebChatChannel,
  WebChatChannelProperties,
  WebChatSite,
  DirectLineChannel,
  DirectLineChannelProperties,
  DirectLineSite,
  TelegramChannel,
  TelegramChannelProperties,
  SmsChannel,
  SmsChannelProperties,
  SlackChannel,
  SlackChannelProperties,
  LineChannel,
  LineChannelProperties,
  LineRegistration,
  DirectLineSpeechChannel,
  DirectLineSpeechChannelProperties,
  Omnichannel,
  TelephonyChannel,
  TelephonyChannelProperties,
  TelephonyPhoneNumbers,
  TelephonyChannelResourceApiConfiguration,
  AcsChatChannel,
  SearchAssistant,
  M365Extensions,
  Site,
  ListChannelWithKeysResponse,
  ChannelSettings,
  SiteInfo,
  Key,
  ConnectionSetting,
  ConnectionSettingProperties,
  ConnectionSettingParameter,
  CheckNameAvailabilityRequestBody,
  CheckNameAvailabilityResponseBody,
  ServiceProviderResponseList,
  ServiceProvider,
  ServiceProviderProperties,
  ServiceProviderParameter,
  ServiceProviderParameterMetadata,
  ServiceProviderParameterMetadataConstraints,
  QnAMakerEndpointKeysRequestBody,
  QnAMakerEndpointKeysResponse,
  HostSettingsResponse,
  OperationResultsDescription,
  KnownOperationResultStatus,
  OperationResultStatus,
  KnownVersions,
} from "./models/index.js";
export { BotServiceClientOptionalParams } from "./api/index.js";
export {
  BotChannelsRegenerateKeysOptionalParams,
  BotChannelsListWithKeysOptionalParams,
  BotChannelsListByResourceGroupOptionalParams,
  BotChannelsDeleteOptionalParams,
  BotChannelsUpdateOptionalParams,
  BotChannelsCreateOptionalParams,
  BotChannelsGetOptionalParams,
} from "./api/botChannels/index.js";
export { BotConnectionOperationGroupListServiceProvidersOptionalParams } from "./api/botConnectionOperationGroup/index.js";
export {
  BotsListByBotResourceOptionalParams,
  BotsCreateSignInUrlOptionalParams,
  BotsListOptionalParams,
  BotsListByResourceGroupOptionalParams,
  BotsDeleteOptionalParams,
  BotsUpdateOptionalParams,
  BotsCreateOptionalParams,
  BotsGetOptionalParams,
} from "./api/bots/index.js";
export { BotsOperationGroupGetCheckNameAvailabilityOptionalParams } from "./api/botsOperationGroup/index.js";
export {
  ConnectionSettingsListWithSecretsOptionalParams,
  ConnectionSettingsListByBotServiceOptionalParams,
  ConnectionSettingsDeleteOptionalParams,
  ConnectionSettingsUpdateOptionalParams,
  ConnectionSettingsCreateOptionalParams,
  ConnectionSettingsGetOptionalParams,
} from "./api/connectionSettings/index.js";
export { HostSettingsOperationGroupGetOptionalParams } from "./api/hostSettingsOperationGroup/index.js";
export {
  NetworkSecurityPerimeterConfigurationsReconcileOptionalParams,
  NetworkSecurityPerimeterConfigurationsListOptionalParams,
  NetworkSecurityPerimeterConfigurationsGetOptionalParams,
} from "./api/networkSecurityPerimeterConfigurations/index.js";
export { OperationResultsOperationGroupGetOptionalParams } from "./api/operationResultsOperationGroup/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  PrivateEndpointConnectionsListOptionalParams,
  PrivateEndpointConnectionsDeleteOptionalParams,
  PrivateEndpointConnectionsCreateOptionalParams,
  PrivateEndpointConnectionsGetOptionalParams,
} from "./api/privateEndpointConnections/index.js";
export { QnAMakerEndpointKeysOperationGroupGetOptionalParams } from "./api/qnAMakerEndpointKeysOperationGroup/index.js";
export {
  BotChannelsOperations,
  BotConnectionOperationGroupOperations,
  BotsOperations,
  BotsOperationGroupOperations,
  ConnectionSettingsOperations,
  HostSettingsOperationGroupOperations,
  NetworkSecurityPerimeterConfigurationsOperations,
  OperationResultsOperationGroupOperations,
  OperationsOperations,
  PrivateEndpointConnectionsOperations,
  QnAMakerEndpointKeysOperationGroupOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
