// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { AzureSphereClient } from "./azureSphereClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Device,
  DeviceProperties,
  KnownProvisioningState,
  ProvisioningState,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  DeviceUpdate,
  DeviceUpdateProperties,
  GenerateCapabilityImageRequest,
  KnownCapabilityType,
  CapabilityType,
  SignedCapabilityImageResponse,
  Deployment,
  DeploymentProperties,
  Image,
  ImageProperties,
  KnownRegionalDataBoundary,
  RegionalDataBoundary,
  KnownImageType,
  ImageType,
  DeviceGroup,
  DeviceGroupProperties,
  KnownOSFeedType,
  OSFeedType,
  KnownUpdatePolicy,
  UpdatePolicy,
  KnownAllowCrashDumpCollection,
  AllowCrashDumpCollection,
  DeviceGroupUpdate,
  DeviceGroupUpdateProperties,
  ClaimDevicesRequest,
  CountDevicesResponse,
  CountElementsResponse,
  Product,
  ProductProperties,
  ProductUpdate,
  ProductUpdateProperties,
  Certificate,
  CertificateProperties,
  KnownCertificateStatus,
  CertificateStatus,
  CertificateChainResponse,
  ProofOfPossessionNonceRequest,
  ProofOfPossessionNonceResponse,
  Catalog,
  CatalogProperties,
  TrackedResource,
  CatalogUpdate,
  ListDeviceGroupsRequest,
  DeviceInsight,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  KnownVersions,
} from "./models/index.js";
export {
  AzureSphereClientOptionalParams,
  DevicesGenerateCapabilityImageOptionalParams,
  DevicesListByDeviceGroupOptionalParams,
  DevicesDeleteOptionalParams,
  DevicesUpdateOptionalParams,
  DevicesCreateOrUpdateOptionalParams,
  DevicesGetOptionalParams,
  DeploymentsListByDeviceGroupOptionalParams,
  DeploymentsDeleteOptionalParams,
  DeploymentsCreateOrUpdateOptionalParams,
  DeploymentsGetOptionalParams,
  DeviceGroupsCountDevicesOptionalParams,
  DeviceGroupsClaimDevicesOptionalParams,
  DeviceGroupsListByProductOptionalParams,
  DeviceGroupsDeleteOptionalParams,
  DeviceGroupsUpdateOptionalParams,
  DeviceGroupsCreateOrUpdateOptionalParams,
  DeviceGroupsGetOptionalParams,
  ProductsGenerateDefaultDeviceGroupsOptionalParams,
  ProductsCountDevicesOptionalParams,
  ProductsListByCatalogOptionalParams,
  ProductsDeleteOptionalParams,
  ProductsUpdateOptionalParams,
  ProductsCreateOrUpdateOptionalParams,
  ProductsGetOptionalParams,
  ImagesListByCatalogOptionalParams,
  ImagesDeleteOptionalParams,
  ImagesCreateOrUpdateOptionalParams,
  ImagesGetOptionalParams,
  CertificatesRetrieveProofOfPossessionNonceOptionalParams,
  CertificatesRetrieveCertChainOptionalParams,
  CertificatesListByCatalogOptionalParams,
  CertificatesGetOptionalParams,
  CatalogsUploadImageOptionalParams,
  CatalogsListDevicesOptionalParams,
  CatalogsListDeviceInsightsOptionalParams,
  CatalogsListDeviceGroupsOptionalParams,
  CatalogsListDeploymentsOptionalParams,
  CatalogsCountDevicesOptionalParams,
  CatalogsListBySubscriptionOptionalParams,
  CatalogsListByResourceGroupOptionalParams,
  CatalogsDeleteOptionalParams,
  CatalogsUpdateOptionalParams,
  CatalogsCreateOrUpdateOptionalParams,
  CatalogsGetOptionalParams,
  OperationsListOptionalParams,
} from "./api/index.js";
export {
  CatalogsOperations,
  CertificatesOperations,
  DeploymentsOperations,
  DeviceGroupsOperations,
  DevicesOperations,
  ImagesOperations,
  OperationsOperations,
  ProductsOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
