// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { DatabaseClient } from "./databaseClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  AutonomousDbVersion,
  AutonomousDbVersionProperties,
  KnownWorkloadType,
  WorkloadType,
  ProxyResource,
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  AutonomousDatabaseNationalCharacterSet,
  AutonomousDatabaseNationalCharacterSetProperties,
  AutonomousDatabaseCharacterSet,
  AutonomousDatabaseCharacterSetProperties,
  AutonomousDatabaseBackup,
  AutonomousDatabaseBackupProperties,
  KnownAutonomousDatabaseBackupLifecycleState,
  AutonomousDatabaseBackupLifecycleState,
  KnownAutonomousDatabaseBackupType,
  AutonomousDatabaseBackupType,
  KnownAzureResourceProvisioningState,
  AzureResourceProvisioningState,
  KnownResourceProvisioningState,
  ResourceProvisioningState,
  AutonomousDatabaseBackupUpdate,
  AutonomousDatabaseBackupUpdateProperties,
  AutonomousDatabase,
  AutonomousDatabaseBaseProperties,
  AutonomousDatabaseBasePropertiesUnion,
  KnownDataBaseType,
  DataBaseType,
  KnownAutonomousMaintenanceScheduleType,
  AutonomousMaintenanceScheduleType,
  KnownComputeModel,
  ComputeModel,
  CustomerContact,
  KnownDisasterRecoveryType,
  DisasterRecoveryType,
  DisasterRecoveryConfigurationDetails,
  AutonomousDatabaseStandbySummary,
  KnownAutonomousDatabaseLifecycleState,
  AutonomousDatabaseLifecycleState,
  KnownLicenseModel,
  LicenseModel,
  ScheduledOperationsType,
  DayOfWeek,
  KnownDayOfWeekName,
  DayOfWeekName,
  ApexDetailsType,
  ConnectionStringType,
  AllConnectionStringType,
  ProfileType,
  KnownConsumerGroup,
  ConsumerGroup,
  KnownHostFormatType,
  HostFormatType,
  KnownProtocolType,
  ProtocolType,
  KnownSessionModeType,
  SessionModeType,
  KnownSyntaxFormatType,
  SyntaxFormatType,
  KnownTlsAuthenticationType,
  TlsAuthenticationType,
  ConnectionUrlType,
  KnownDataSafeStatusType,
  DataSafeStatusType,
  KnownDatabaseEditionType,
  DatabaseEditionType,
  LongTermBackUpScheduleDetails,
  KnownRepeatCadenceType,
  RepeatCadenceType,
  KnownOpenModeType,
  OpenModeType,
  KnownOperationsInsightsStatusType,
  OperationsInsightsStatusType,
  KnownPermissionLevelType,
  PermissionLevelType,
  KnownRoleType,
  RoleType,
  AutonomousDatabaseProperties,
  AutonomousDatabaseCloneProperties,
  KnownSourceType,
  SourceType,
  KnownCloneType,
  CloneType,
  KnownRefreshableModelType,
  RefreshableModelType,
  KnownRefreshableStatusType,
  RefreshableStatusType,
  AutonomousDatabaseCrossRegionDisasterRecoveryProperties,
  AutonomousDatabaseFromBackupTimestampProperties,
  TrackedResource,
  AutonomousDatabaseUpdate,
  AutonomousDatabaseUpdateProperties,
  PeerDbDetails,
  GenerateAutonomousDatabaseWalletDetails,
  KnownGenerateType,
  GenerateType,
  AutonomousDatabaseWalletFile,
  RestoreAutonomousDatabaseDetails,
  DnsPrivateZone,
  DnsPrivateZoneProperties,
  KnownDnsPrivateZonesLifecycleState,
  DnsPrivateZonesLifecycleState,
  KnownZoneType,
  ZoneType,
  DnsPrivateView,
  DnsPrivateViewProperties,
  KnownDnsPrivateViewsLifecycleState,
  DnsPrivateViewsLifecycleState,
  DbSystemShape,
  DbSystemShapeProperties,
  GiVersion,
  GiVersionProperties,
  DbNode,
  DbNodeProperties,
  KnownDbNodeProvisioningState,
  DbNodeProvisioningState,
  KnownDbNodeMaintenanceType,
  DbNodeMaintenanceType,
  DbNodeAction,
  KnownDbNodeActionEnum,
  DbNodeActionEnum,
  OracleSubscription,
  OracleSubscriptionProperties,
  KnownOracleSubscriptionProvisioningState,
  OracleSubscriptionProvisioningState,
  KnownCloudAccountProvisioningState,
  CloudAccountProvisioningState,
  KnownIntent,
  Intent,
  KnownAddSubscriptionOperationState,
  AddSubscriptionOperationState,
  Plan,
  OracleSubscriptionUpdate,
  PlanUpdate,
  OracleSubscriptionUpdateProperties,
  AzureSubscriptions,
  SystemVersion,
  SystemVersionProperties,
  VirtualNetworkAddress,
  VirtualNetworkAddressProperties,
  KnownVirtualNetworkAddressLifecycleState,
  VirtualNetworkAddressLifecycleState,
  CloudVmCluster,
  CloudVmClusterProperties,
  KnownDiskRedundancy,
  DiskRedundancy,
  KnownCloudVmClusterLifecycleState,
  CloudVmClusterLifecycleState,
  NsgCidr,
  PortRange,
  DataCollectionOptions,
  ExadataIormConfig,
  DbIormConfig,
  KnownIormLifecycleState,
  IormLifecycleState,
  KnownObjective,
  Objective,
  CloudVmClusterUpdate,
  CloudVmClusterUpdateProperties,
  AddRemoveDbNode,
  PrivateIpAddressesFilter,
  PrivateIpAddressProperties,
  DbServer,
  DbServerProperties,
  DbServerPatchingDetails,
  KnownDbServerPatchingStatus,
  DbServerPatchingStatus,
  KnownDbServerProvisioningState,
  DbServerProvisioningState,
  CloudExadataInfrastructure,
  CloudExadataInfrastructureProperties,
  MaintenanceWindow,
  KnownPreference,
  Preference,
  Month,
  KnownMonthName,
  MonthName,
  KnownPatchingMode,
  PatchingMode,
  EstimatedPatchingTime,
  KnownCloudExadataInfrastructureLifecycleState,
  CloudExadataInfrastructureLifecycleState,
  CloudExadataInfrastructureUpdate,
  CloudExadataInfrastructureUpdateProperties,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  KnownVersions,
} from "./models/index.js";
export { DatabaseClientOptionalParams } from "./api/index.js";
export {
  AutonomousDatabaseBackupsListByAutonomousDatabaseOptionalParams,
  AutonomousDatabaseBackupsUpdateOptionalParams,
  AutonomousDatabaseBackupsCreateOrUpdateOptionalParams,
  AutonomousDatabaseBackupsDeleteOptionalParams,
  AutonomousDatabaseBackupsGetOptionalParams,
} from "./api/autonomousDatabaseBackups/index.js";
export {
  AutonomousDatabaseCharacterSetsListByLocationOptionalParams,
  AutonomousDatabaseCharacterSetsGetOptionalParams,
} from "./api/autonomousDatabaseCharacterSets/index.js";
export {
  AutonomousDatabaseNationalCharacterSetsListByLocationOptionalParams,
  AutonomousDatabaseNationalCharacterSetsGetOptionalParams,
} from "./api/autonomousDatabaseNationalCharacterSets/index.js";
export {
  AutonomousDatabasesChangeDisasterRecoveryConfigurationOptionalParams,
  AutonomousDatabasesShrinkOptionalParams,
  AutonomousDatabasesRestoreOptionalParams,
  AutonomousDatabasesGenerateWalletOptionalParams,
  AutonomousDatabasesFailoverOptionalParams,
  AutonomousDatabasesSwitchoverOptionalParams,
  AutonomousDatabasesListByResourceGroupOptionalParams,
  AutonomousDatabasesCreateOrUpdateOptionalParams,
  AutonomousDatabasesDeleteOptionalParams,
  AutonomousDatabasesUpdateOptionalParams,
  AutonomousDatabasesGetOptionalParams,
  AutonomousDatabasesListBySubscriptionOptionalParams,
} from "./api/autonomousDatabases/index.js";
export {
  AutonomousDatabaseVersionsListByLocationOptionalParams,
  AutonomousDatabaseVersionsGetOptionalParams,
} from "./api/autonomousDatabaseVersions/index.js";
export {
  CloudExadataInfrastructuresAddStorageCapacityOptionalParams,
  CloudExadataInfrastructuresListByResourceGroupOptionalParams,
  CloudExadataInfrastructuresCreateOrUpdateOptionalParams,
  CloudExadataInfrastructuresDeleteOptionalParams,
  CloudExadataInfrastructuresUpdateOptionalParams,
  CloudExadataInfrastructuresGetOptionalParams,
  CloudExadataInfrastructuresListBySubscriptionOptionalParams,
} from "./api/cloudExadataInfrastructures/index.js";
export {
  CloudVmClustersListPrivateIpAddressesOptionalParams,
  CloudVmClustersRemoveVmsOptionalParams,
  CloudVmClustersAddVmsOptionalParams,
  CloudVmClustersListByResourceGroupOptionalParams,
  CloudVmClustersCreateOrUpdateOptionalParams,
  CloudVmClustersDeleteOptionalParams,
  CloudVmClustersUpdateOptionalParams,
  CloudVmClustersGetOptionalParams,
  CloudVmClustersListBySubscriptionOptionalParams,
} from "./api/cloudVmClusters/index.js";
export {
  DbNodesActionOptionalParams,
  DbNodesListByCloudVmClusterOptionalParams,
  DbNodesGetOptionalParams,
} from "./api/dbNodes/index.js";
export {
  DbServersListByCloudExadataInfrastructureOptionalParams,
  DbServersGetOptionalParams,
} from "./api/dbServers/index.js";
export {
  DbSystemShapesListByLocationOptionalParams,
  DbSystemShapesGetOptionalParams,
} from "./api/dbSystemShapes/index.js";
export {
  DnsPrivateViewsListByLocationOptionalParams,
  DnsPrivateViewsGetOptionalParams,
} from "./api/dnsPrivateViews/index.js";
export {
  DnsPrivateZonesListByLocationOptionalParams,
  DnsPrivateZonesGetOptionalParams,
} from "./api/dnsPrivateZones/index.js";
export {
  GiVersionsListByLocationOptionalParams,
  GiVersionsGetOptionalParams,
} from "./api/giVersions/index.js";
export { OperationsListOptionalParams } from "./api/operations/index.js";
export {
  OracleSubscriptionsAddAzureSubscriptionsOptionalParams,
  OracleSubscriptionsListActivationLinksOptionalParams,
  OracleSubscriptionsListSaasSubscriptionDetailsOptionalParams,
  OracleSubscriptionsListCloudAccountDetailsOptionalParams,
  OracleSubscriptionsCreateOrUpdateOptionalParams,
  OracleSubscriptionsDeleteOptionalParams,
  OracleSubscriptionsUpdateOptionalParams,
  OracleSubscriptionsGetOptionalParams,
  OracleSubscriptionsListBySubscriptionOptionalParams,
} from "./api/oracleSubscriptions/index.js";
export {
  SystemVersionsListByLocationOptionalParams,
  SystemVersionsGetOptionalParams,
} from "./api/systemVersions/index.js";
export {
  VirtualNetworkAddressesListByCloudVmClusterOptionalParams,
  VirtualNetworkAddressesCreateOrUpdateOptionalParams,
  VirtualNetworkAddressesDeleteOptionalParams,
  VirtualNetworkAddressesGetOptionalParams,
} from "./api/virtualNetworkAddresses/index.js";
export {
  AutonomousDatabaseBackupsOperations,
  AutonomousDatabaseCharacterSetsOperations,
  AutonomousDatabaseNationalCharacterSetsOperations,
  AutonomousDatabasesOperations,
  AutonomousDatabaseVersionsOperations,
  CloudExadataInfrastructuresOperations,
  CloudVmClustersOperations,
  DbNodesOperations,
  DbServersOperations,
  DbSystemShapesOperations,
  DnsPrivateViewsOperations,
  DnsPrivateZonesOperations,
  GiVersionsOperations,
  OperationsOperations,
  OracleSubscriptionsOperations,
  SystemVersionsOperations,
  VirtualNetworkAddressesOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
