/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator, PageSettings } from "@azure/core-paging";
import { setContinuationToken } from "../pagingHelper";
import { ContainerGroupProfileOperations } from "../operationsInterfaces";
import * as coreClient from "@azure/core-client";
import * as Mappers from "../models/mappers";
import * as Parameters from "../models/parameters";
import { ContainerInstanceManagementClient } from "../containerInstanceManagementClient";
import {
  SimplePollerLike,
  OperationState,
  createHttpPoller,
} from "@azure/core-lro";
import { createLroSpec } from "../lroImpl";
import {
  ContainerGroupProfile,
  ContainerGroupProfileListBySubscriptionNextOptionalParams,
  ContainerGroupProfileListBySubscriptionOptionalParams,
  ContainerGroupProfileListBySubscriptionResponse,
  ContainerGroupProfileListByResourceGroupNextOptionalParams,
  ContainerGroupProfileListByResourceGroupOptionalParams,
  ContainerGroupProfileListByResourceGroupResponse,
  ContainerGroupProfileCreateOrUpdateOptionalParams,
  ContainerGroupProfileCreateOrUpdateResponse,
  ContainerGroupProfileUpdateOptionalParams,
  ContainerGroupProfileUpdateResponse,
  ContainerGroupProfileGetOptionalParams,
  ContainerGroupProfileGetResponse,
  ContainerGroupProfileDeleteOptionalParams,
  ContainerGroupProfileDeleteResponse,
  ContainerGroupProfileListBySubscriptionNextResponse,
  ContainerGroupProfileListByResourceGroupNextResponse,
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Class containing ContainerGroupProfileOperations operations. */
export class ContainerGroupProfileOperationsImpl
  implements ContainerGroupProfileOperations
{
  private readonly client: ContainerInstanceManagementClient;

  /**
   * Initialize a new instance of the class ContainerGroupProfileOperations class.
   * @param client Reference to the service client
   */
  constructor(client: ContainerInstanceManagementClient) {
    this.client = client;
  }

  /**
   * Gets a list of all container group profiles under a subscription.
   * @param options The options parameters.
   */
  public listBySubscription(
    options?: ContainerGroupProfileListBySubscriptionOptionalParams,
  ): PagedAsyncIterableIterator<ContainerGroupProfile> {
    const iter = this.listBySubscriptionPagingAll(options);
    return {
      next() {
        return iter.next();
      },
      [Symbol.asyncIterator]() {
        return this;
      },
      byPage: (settings?: PageSettings) => {
        if (settings?.maxPageSize) {
          throw new Error("maxPageSize is not supported by this operation.");
        }
        return this.listBySubscriptionPagingPage(options, settings);
      },
    };
  }

  private async *listBySubscriptionPagingPage(
    options?: ContainerGroupProfileListBySubscriptionOptionalParams,
    settings?: PageSettings,
  ): AsyncIterableIterator<ContainerGroupProfile[]> {
    let result: ContainerGroupProfileListBySubscriptionResponse;
    let continuationToken = settings?.continuationToken;
    if (!continuationToken) {
      result = await this._listBySubscription(options);
      let page = result.value || [];
      continuationToken = result.nextLink;
      setContinuationToken(page, continuationToken);
      yield page;
    }
    while (continuationToken) {
      result = await this._listBySubscriptionNext(continuationToken, options);
      continuationToken = result.nextLink;
      let page = result.value || [];
      setContinuationToken(page, continuationToken);
      yield page;
    }
  }

  private async *listBySubscriptionPagingAll(
    options?: ContainerGroupProfileListBySubscriptionOptionalParams,
  ): AsyncIterableIterator<ContainerGroupProfile> {
    for await (const page of this.listBySubscriptionPagingPage(options)) {
      yield* page;
    }
  }

  /**
   * Gets a list of all container group profiles under a resource group.
   * @param resourceGroupName The name of the resource group.
   * @param options The options parameters.
   */
  public listByResourceGroup(
    resourceGroupName: string,
    options?: ContainerGroupProfileListByResourceGroupOptionalParams,
  ): PagedAsyncIterableIterator<ContainerGroupProfile> {
    const iter = this.listByResourceGroupPagingAll(resourceGroupName, options);
    return {
      next() {
        return iter.next();
      },
      [Symbol.asyncIterator]() {
        return this;
      },
      byPage: (settings?: PageSettings) => {
        if (settings?.maxPageSize) {
          throw new Error("maxPageSize is not supported by this operation.");
        }
        return this.listByResourceGroupPagingPage(
          resourceGroupName,
          options,
          settings,
        );
      },
    };
  }

  private async *listByResourceGroupPagingPage(
    resourceGroupName: string,
    options?: ContainerGroupProfileListByResourceGroupOptionalParams,
    settings?: PageSettings,
  ): AsyncIterableIterator<ContainerGroupProfile[]> {
    let result: ContainerGroupProfileListByResourceGroupResponse;
    let continuationToken = settings?.continuationToken;
    if (!continuationToken) {
      result = await this._listByResourceGroup(resourceGroupName, options);
      let page = result.value || [];
      continuationToken = result.nextLink;
      setContinuationToken(page, continuationToken);
      yield page;
    }
    while (continuationToken) {
      result = await this._listByResourceGroupNext(
        resourceGroupName,
        continuationToken,
        options,
      );
      continuationToken = result.nextLink;
      let page = result.value || [];
      setContinuationToken(page, continuationToken);
      yield page;
    }
  }

  private async *listByResourceGroupPagingAll(
    resourceGroupName: string,
    options?: ContainerGroupProfileListByResourceGroupOptionalParams,
  ): AsyncIterableIterator<ContainerGroupProfile> {
    for await (const page of this.listByResourceGroupPagingPage(
      resourceGroupName,
      options,
    )) {
      yield* page;
    }
  }

  /**
   * Gets a list of all container group profiles under a subscription.
   * @param options The options parameters.
   */
  private _listBySubscription(
    options?: ContainerGroupProfileListBySubscriptionOptionalParams,
  ): Promise<ContainerGroupProfileListBySubscriptionResponse> {
    return this.client.sendOperationRequest(
      { options },
      listBySubscriptionOperationSpec,
    );
  }

  /**
   * Gets a list of all container group profiles under a resource group.
   * @param resourceGroupName The name of the resource group.
   * @param options The options parameters.
   */
  private _listByResourceGroup(
    resourceGroupName: string,
    options?: ContainerGroupProfileListByResourceGroupOptionalParams,
  ): Promise<ContainerGroupProfileListByResourceGroupResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, options },
      listByResourceGroupOperationSpec,
    );
  }

  /**
   * Create a CGProfile if it doesn't exist or update an existing CGProfile.
   * @param resourceGroupName The name of the resource group.
   * @param containerGroupProfileName ContainerGroupProfile name.
   * @param containerGroupProfile The ContainerGroupProfile object.
   * @param options The options parameters.
   */
  createOrUpdate(
    resourceGroupName: string,
    containerGroupProfileName: string,
    containerGroupProfile: ContainerGroupProfile,
    options?: ContainerGroupProfileCreateOrUpdateOptionalParams,
  ): Promise<ContainerGroupProfileCreateOrUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        containerGroupProfileName,
        containerGroupProfile,
        options,
      },
      createOrUpdateOperationSpec,
    );
  }

  /**
   * Update a specified container group profile.
   * @param resourceGroupName The name of the resource group.
   * @param containerGroupProfileName ContainerGroupProfile name.
   * @param options The options parameters.
   */
  update(
    resourceGroupName: string,
    containerGroupProfileName: string,
    options?: ContainerGroupProfileUpdateOptionalParams,
  ): Promise<ContainerGroupProfileUpdateResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, containerGroupProfileName, options },
      updateOperationSpec,
    );
  }

  /**
   * Get the properties of the specified container group profile.
   * @param resourceGroupName The name of the resource group.
   * @param containerGroupProfileName ContainerGroupProfile name.
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    containerGroupProfileName: string,
    options?: ContainerGroupProfileGetOptionalParams,
  ): Promise<ContainerGroupProfileGetResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, containerGroupProfileName, options },
      getOperationSpec,
    );
  }

  /**
   * Deletes a container group profile.
   * @param resourceGroupName The name of the resource group.
   * @param containerGroupProfileName ContainerGroupProfile name.
   * @param options The options parameters.
   */
  async beginDelete(
    resourceGroupName: string,
    containerGroupProfileName: string,
    options?: ContainerGroupProfileDeleteOptionalParams,
  ): Promise<
    SimplePollerLike<
      OperationState<ContainerGroupProfileDeleteResponse>,
      ContainerGroupProfileDeleteResponse
    >
  > {
    const directSendOperation = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec,
    ): Promise<ContainerGroupProfileDeleteResponse> => {
      return this.client.sendOperationRequest(args, spec);
    };
    const sendOperationFn = async (
      args: coreClient.OperationArguments,
      spec: coreClient.OperationSpec,
    ) => {
      let currentRawResponse: coreClient.FullOperationResponse | undefined =
        undefined;
      const providedCallback = args.options?.onResponse;
      const callback: coreClient.RawResponseCallback = (
        rawResponse: coreClient.FullOperationResponse,
        flatResponse: unknown,
      ) => {
        currentRawResponse = rawResponse;
        providedCallback?.(rawResponse, flatResponse);
      };
      const updatedArgs = {
        ...args,
        options: {
          ...args.options,
          onResponse: callback,
        },
      };
      const flatResponse = await directSendOperation(updatedArgs, spec);
      return {
        flatResponse,
        rawResponse: {
          statusCode: currentRawResponse!.status,
          body: currentRawResponse!.parsedBody,
          headers: currentRawResponse!.headers.toJSON(),
        },
      };
    };

    const lro = createLroSpec({
      sendOperationFn,
      args: { resourceGroupName, containerGroupProfileName, options },
      spec: deleteOperationSpec,
    });
    const poller = await createHttpPoller<
      ContainerGroupProfileDeleteResponse,
      OperationState<ContainerGroupProfileDeleteResponse>
    >(lro, {
      restoreFrom: options?.resumeFrom,
      intervalInMs: options?.updateIntervalInMs,
    });
    await poller.poll();
    return poller;
  }

  /**
   * Deletes a container group profile.
   * @param resourceGroupName The name of the resource group.
   * @param containerGroupProfileName ContainerGroupProfile name.
   * @param options The options parameters.
   */
  async beginDeleteAndWait(
    resourceGroupName: string,
    containerGroupProfileName: string,
    options?: ContainerGroupProfileDeleteOptionalParams,
  ): Promise<ContainerGroupProfileDeleteResponse> {
    const poller = await this.beginDelete(
      resourceGroupName,
      containerGroupProfileName,
      options,
    );
    return poller.pollUntilDone();
  }

  /**
   * ListBySubscriptionNext
   * @param nextLink The nextLink from the previous successful call to the ListBySubscription method.
   * @param options The options parameters.
   */
  private _listBySubscriptionNext(
    nextLink: string,
    options?: ContainerGroupProfileListBySubscriptionNextOptionalParams,
  ): Promise<ContainerGroupProfileListBySubscriptionNextResponse> {
    return this.client.sendOperationRequest(
      { nextLink, options },
      listBySubscriptionNextOperationSpec,
    );
  }

  /**
   * ListByResourceGroupNext
   * @param resourceGroupName The name of the resource group.
   * @param nextLink The nextLink from the previous successful call to the ListByResourceGroup method.
   * @param options The options parameters.
   */
  private _listByResourceGroupNext(
    resourceGroupName: string,
    nextLink: string,
    options?: ContainerGroupProfileListByResourceGroupNextOptionalParams,
  ): Promise<ContainerGroupProfileListByResourceGroupNextResponse> {
    return this.client.sendOperationRequest(
      { resourceGroupName, nextLink, options },
      listByResourceGroupNextOperationSpec,
    );
  }
}
// Operation Specifications
const serializer = coreClient.createSerializer(Mappers, /* isXml */ false);

const listBySubscriptionOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/providers/Microsoft.ContainerInstance/containerGroupProfiles",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.ContainerGroupProfileListResult,
    },
    default: {
      bodyMapper: Mappers.CloudError,
    },
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [Parameters.$host, Parameters.subscriptionId],
  headerParameters: [Parameters.accept],
  serializer,
};
const listByResourceGroupOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerInstance/containerGroupProfiles",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.ContainerGroupProfileListResult,
    },
    default: {
      bodyMapper: Mappers.CloudError,
    },
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
const createOrUpdateOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerInstance/containerGroupProfiles/{containerGroupProfileName}",
  httpMethod: "PUT",
  responses: {
    200: {
      bodyMapper: Mappers.ContainerGroupProfile,
      headersMapper: Mappers.ContainerGroupProfileCreateOrUpdateHeaders,
    },
    201: {
      bodyMapper: Mappers.ContainerGroupProfile,
      headersMapper: Mappers.ContainerGroupProfileCreateOrUpdateHeaders,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  requestBody: Parameters.containerGroupProfile,
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.containerGroupProfileName,
  ],
  headerParameters: [Parameters.accept, Parameters.contentType],
  mediaType: "json",
  serializer,
};
const updateOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerInstance/containerGroupProfiles/{containerGroupProfileName}",
  httpMethod: "PATCH",
  responses: {
    200: {
      bodyMapper: Mappers.ContainerGroupProfile,
      headersMapper: Mappers.ContainerGroupProfileUpdateHeaders,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  requestBody: Parameters.containerGroupProfile1,
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.containerGroupProfileName,
  ],
  headerParameters: [Parameters.accept, Parameters.contentType],
  mediaType: "json",
  serializer,
};
const getOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerInstance/containerGroupProfiles/{containerGroupProfileName}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.ContainerGroupProfile,
    },
    default: {
      bodyMapper: Mappers.CloudError,
    },
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.containerGroupProfileName,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
const deleteOperationSpec: coreClient.OperationSpec = {
  path: "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerInstance/containerGroupProfiles/{containerGroupProfileName}",
  httpMethod: "DELETE",
  responses: {
    200: {
      headersMapper: Mappers.ContainerGroupProfileDeleteHeaders,
    },
    201: {
      headersMapper: Mappers.ContainerGroupProfileDeleteHeaders,
    },
    202: {
      headersMapper: Mappers.ContainerGroupProfileDeleteHeaders,
    },
    204: {
      headersMapper: Mappers.ContainerGroupProfileDeleteHeaders,
    },
    default: {
      bodyMapper: Mappers.ErrorResponse,
    },
  },
  queryParameters: [Parameters.apiVersion],
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.containerGroupProfileName,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
const listBySubscriptionNextOperationSpec: coreClient.OperationSpec = {
  path: "{nextLink}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.ContainerGroupProfileListResult,
    },
    default: {
      bodyMapper: Mappers.CloudError,
    },
  },
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.nextLink,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
const listByResourceGroupNextOperationSpec: coreClient.OperationSpec = {
  path: "{nextLink}",
  httpMethod: "GET",
  responses: {
    200: {
      bodyMapper: Mappers.ContainerGroupProfileListResult,
    },
    default: {
      bodyMapper: Mappers.CloudError,
    },
  },
  urlParameters: [
    Parameters.$host,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.nextLink,
  ],
  headerParameters: [Parameters.accept],
  serializer,
};
