# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/mongocluster-new/
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/mongocluster-new/
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: mongocluster-new
    Artifacts:
      - name: azure-arm-mongocluster-new
        safeName: azurearmmongoclusternew
