# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
                
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/manufacturingdatasolution/
pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
    exclude:
      - feature/v4
  paths:
    include:
      - sdk/manufacturingdatasolution/
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: manufacturingdatasolution
    Artifacts:
      - name: azure-rest-microsoft-industry-manufacturing-mds-copilot
        safeName: azurerestmicrosoftindustrymanufacturingmdscopilot
