// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export {
  DeviceRegistryClient,
  DeviceRegistryClientOptionalParams,
} from "./deviceRegistryClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  Resource,
  SystemData,
  KnownCreatedByType,
  CreatedByType,
  ProxyResource,
  BillingContainer,
  BillingContainerProperties,
  KnownResourceProvisioningState,
  ResourceProvisioningState,
  ErrorResponse,
  ErrorDetail,
  ErrorAdditionalInfo,
  TrackedResource,
  AssetEndpointProfile,
  AssetEndpointProfileProperties,
  Authentication,
  KnownAuthenticationMethod,
  AuthenticationMethod,
  UsernamePasswordCredentials,
  X509Credentials,
  AssetEndpointProfileStatus,
  AssetEndpointProfileStatusError,
  ExtendedLocation,
  AssetEndpointProfileUpdate,
  AssetEndpointProfileUpdateProperties,
  Asset,
  AssetProperties,
  Topic,
  KnownTopicRetainType,
  TopicRetainType,
  Dataset,
  DataPointBase,
  DataPoint,
  KnownDataPointObservabilityMode,
  DataPointObservabilityMode,
  EventBase,
  Event,
  KnownEventObservabilityMode,
  EventObservabilityMode,
  AssetStatus,
  AssetStatusError,
  AssetStatusDataset,
  MessageSchemaReference,
  AssetStatusEvent,
  AssetUpdate,
  AssetUpdateProperties,
  OperationStatusResult,
  Operation,
  OperationDisplay,
  KnownOrigin,
  Origin,
  KnownActionType,
  ActionType,
  Versions,
  ProvisioningState,
  OperationsListOptionalParams,
  OperationStatusGetOptionalParams,
  AssetsGetOptionalParams,
  AssetsCreateOrReplaceOptionalParams,
  AssetsUpdateOptionalParams,
  AssetsDeleteOptionalParams,
  AssetsListByResourceGroupOptionalParams,
  AssetsListBySubscriptionOptionalParams,
  AssetEndpointProfilesGetOptionalParams,
  AssetEndpointProfilesCreateOrReplaceOptionalParams,
  AssetEndpointProfilesUpdateOptionalParams,
  AssetEndpointProfilesDeleteOptionalParams,
  AssetEndpointProfilesListByResourceGroupOptionalParams,
  AssetEndpointProfilesListBySubscriptionOptionalParams,
  BillingContainersGetOptionalParams,
  BillingContainersListBySubscriptionOptionalParams,
} from "./models/index.js";
export {
  AssetEndpointProfilesOperations,
  AssetsOperations,
  BillingContainersOperations,
  OperationsOperations,
  OperationStatusOperations,
} from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
