/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  SqlAvailabilityGroupDatabaseResource,
  SqlAvailabilityGroupDatabasesListOptionalParams,
  SqlAvailabilityGroupDatabasesCreateOptionalParams,
  SqlAvailabilityGroupDatabasesCreateResponse,
  SqlAvailabilityGroupDatabasesDeleteOptionalParams,
  SqlAvailabilityGroupDatabasesGetOptionalParams,
  SqlAvailabilityGroupDatabasesGetResponse,
  SqlAvailabilityGroupDatabaseUpdate,
  SqlAvailabilityGroupDatabasesUpdateOptionalParams,
  SqlAvailabilityGroupDatabasesUpdateResponse
} from "../models";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a SqlAvailabilityGroupDatabases. */
export interface SqlAvailabilityGroupDatabases {
  /**
   * List the Availability Group Databases associated with the given Arc Sql AG.
   * @param resourceGroupName The name of the Azure resource group
   * @param sqlAvailabilityGroupName Name of SQL Availability Group
   * @param options The options parameters.
   */
  list(
    resourceGroupName: string,
    sqlAvailabilityGroupName: string,
    options?: SqlAvailabilityGroupDatabasesListOptionalParams
  ): PagedAsyncIterableIterator<SqlAvailabilityGroupDatabaseResource>;
  /**
   * Creates or update database in an Arc Sql Availability Group.
   * @param resourceGroupName The name of the Azure resource group
   * @param sqlAvailabilityGroupDatabaseName Name of SQL Availability Group Database
   * @param sqlAvailabilityGroupName Name of SQL Availability Group
   * @param sqlAvailabilityGroupDatabaseResource The request body for availability group databases
   *                                             resource.
   * @param options The options parameters.
   */
  create(
    resourceGroupName: string,
    sqlAvailabilityGroupDatabaseName: string,
    sqlAvailabilityGroupName: string,
    sqlAvailabilityGroupDatabaseResource: SqlAvailabilityGroupDatabaseResource,
    options?: SqlAvailabilityGroupDatabasesCreateOptionalParams
  ): Promise<SqlAvailabilityGroupDatabasesCreateResponse>;
  /**
   * Deletes an Arc Sql availability group database resource.
   * @param resourceGroupName The name of the Azure resource group
   * @param sqlAvailabilityGroupDatabaseName Name of SQL Availability Group Database
   * @param sqlAvailabilityGroupName Name of SQL Availability Group
   * @param options The options parameters.
   */
  delete(
    resourceGroupName: string,
    sqlAvailabilityGroupDatabaseName: string,
    sqlAvailabilityGroupName: string,
    options?: SqlAvailabilityGroupDatabasesDeleteOptionalParams
  ): Promise<void>;
  /**
   * Retrieves an Arc Sql availability group database resource.
   * @param resourceGroupName The name of the Azure resource group
   * @param sqlAvailabilityGroupDatabaseName Name of SQL Availability Group Database
   * @param sqlAvailabilityGroupName Name of SQL Availability Group
   * @param options The options parameters.
   */
  get(
    resourceGroupName: string,
    sqlAvailabilityGroupDatabaseName: string,
    sqlAvailabilityGroupName: string,
    options?: SqlAvailabilityGroupDatabasesGetOptionalParams
  ): Promise<SqlAvailabilityGroupDatabasesGetResponse>;
  /**
   * Updates an existing Availability Group Database.
   * @param resourceGroupName The name of the Azure resource group
   * @param sqlAvailabilityGroupDatabaseName Name of SQL Availability Group Database
   * @param sqlAvailabilityGroupName Name of SQL Availability Group
   * @param sqlAvailabilityGroupDatabaseUpdate The update availability group database resource.
   * @param options The options parameters.
   */
  update(
    resourceGroupName: string,
    sqlAvailabilityGroupDatabaseName: string,
    sqlAvailabilityGroupName: string,
    sqlAvailabilityGroupDatabaseUpdate: SqlAvailabilityGroupDatabaseUpdate,
    options?: SqlAvailabilityGroupDatabasesUpdateOptionalParams
  ): Promise<SqlAvailabilityGroupDatabasesUpdateResponse>;
}
